### ISSUE TITLE
Replace the current dbus IPC with other

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/project#10]
Today stratisd has a dbus API which is leveraged by the stratis command line interface.  Dbus is very feature rich, but suffers from the following issues/complexity when utilized for stratisd.

* Stratisd needs to run in initrd for supporting root fs on stratis.  Thus we need to compile 2 different versions of stratis, one with dbus support, one without as initrd does not include the needed dbus shared libraries.

* Stratisd needs to start before file systems get mounted.  Dbus is unavailable until after file systems are mounted.  Today the daemon has to periodically attempt to bring up the dbus interface until it can.  This can result in missing a real miss configuration issue like: https://github.com/stratis-storage/stratisd/issues/1401 .  There is also the other problem of when dbus was, but is no longer available, ref. https://github.com/stratis-storage/stratisd/issues/1078 .  Another issue caused by this requirement: https://bugzilla.redhat.com/show_bug.cgi?id=1646938

* Early boot environment does not have dbus support, thus if the system is unable to find a Stratis based file system in fstab, the system ends up in the emergency shell.  With no dbus support we have no way of interacting with the daemon, ref. https://github.com/stratis-storage/stratisd/issues/1034

* If dracut is unable to find root fs we could potentially be placed into dracut debug shell for investigation.  However, in this environment we have no way of interacting with the stratisd daemon, ref. https://github.com/stratis-storage/stratisd/issues/1031

### Replacing dbus with some other IPC mechanism, eg. varlink ###

Pros

* Complexity is reduced as we only need one code path, no conditional compilation, and a single binary for all run-times
* We have an IPC API that would work in all required run-times
* We would have a CLI that is usable in all environments for query and possible correction
* Corrects all the described issues listed above
* Fewer package dependencies (potentially)
* Smaller run-time requirements
* Allows better integration with SID, because when running in the initramfs SID would have no way to communicate with stratisd
* Non dbus IPC is dramatically simpler for clients if we select an IPC like JSON-RPC
* We no longer need to solve a number of different problems as they simply go away

Cons

* Need to re-write the CLI in a non-interpreted language, so that it can be included in the initrd
* Need to replace dbus code in stratisd with varlink or other suitable IPC functionality
* The command line interface doesn't need all the features of dbus.  GUI applications would benefit from the object manager interface and the other standard dbus interfaces that stratis provides.

### Other IPC mechanisms ###
Some of the ways to communicate between processes on Linux
* Signals
* Shared memory
* Pipes (anonymous & Named)
* Socket/Stream interface (Network, Unix domain, etc.)
* Semaphores
* Files on Filesystem

As we need something that can serve in a client/server architecture and also requires that only `root` privileged process modify storage the unix domain socket is the easiest without us requiring some type of authentication across the transport, especially when we can use abstract namespace.

### Different protocols based on stream transport
* RPC
* XML-RPC
* JSON-RPC
* Varlink
* SOAP
* REST
* gRPC
* CORBA
* ZeroC
* ...

**Comment by mulkieran** [comment]
We can decide to supplement the D-Bus IPC mechanism w/ another, to replace it with another, or to stick with it. We will do that based on our long-term strategic goals. At this point, we have no reason, and therefore no plan, to make a change.
