### ISSUE TITLE
Raise RuntimeError instead of using assert in test framework and infrastructure in order to distinguish test errors from test failures

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#105]
~~Old title: Set failureException to None in subclasses of UnitTest~~

~~Otherwise, it seems that now and perhaps for quite a while, an assertion failure will be interpreted as a test error when it should be interpreted as a test failure.~~

Actually, so long as we raise any exception that is not a subtype of ```AssertionError``` we can get the distinction we want. We can start in the blackbox tests and go on from there. Since we followed a pretty good discipline in the blackbox tests, this is roughly finding every ```assert``` command and replacing it with an equivalent ```RuntimeError```.

We can only do this for the blackbox tests right now, because pytest ignores the ERROR/FAILURE distinction in generating its reports. Should we switch to using pure unittest?

- [x] blackbox tests in stratis-cli
- [x] udev tests in stratisd
- [ ]  ~~all Python-based tests in stratisd~~ Assuming we remove the dbus_interface tests in stratisd this is all done.
- [x]  whitebox tests in stratis-cli

Example in ```stratis_cli_cert.py```.

```
def make_test_pool(pool_disks):
    """
    Create a test pool that will later get destroyed
    :param list pool_disks: List of disks with which the pool will be created
    :return: Name of the created pool
    """
    pool_name = p_n()
    (return_code, _, stderr) = exec_test_command(
        [STRATIS_CLI, "pool", "create", pool_name] + pool_disks
    )
    assert return_code == 0, "return_code: %s, stderr: %s" % (return_code, stderr)
    return pool_name
```

should become something like:

```
def make_test_pool(pool_disks):
    """
    Create a test pool that will later get destroyed
    :param list pool_disks: List of disks with which the pool will be created
    :return: Name of the created pool
    """
    pool_name = p_n()
    (return_code, _, stderr) = exec_test_command(
        [STRATIS_CLI, "pool", "create", pool_name] + pool_disks
    )
    if return_code != 0:
         raise RuntimeError("Expected return code of 0; actual return_code: %s, stderr: %s" % (return_code, stderr)) 
    return pool_name
```

**Comment by mulkieran** [comment]
I was misinformed. In order to distinguish test errors from test failures it would be necessary to make the exceptions that cause test errors to be some exception type that it not a subtype of AssertionError. I think that failureException was probably added so that new test frameworks could use an exception that was not an AssertionError. But unittest's errors do seem to inhabit AssertionError.

**Comment by mulkieran** [comment]
We have no reason to go any further with this until we have more pure unittest test suites.

**Comment by mulkieran** [comment]
@bgurney-rh All stratis-cli tests can now be adjusted to use RuntimeError's. However, the unittest tests don't need it, the monkey_patching tests don't need it directly, and the integration tests will need a new kind of treatment, since they spawn processes and use the ```RUNNER``` method. So there is just one place to work on: the ```setUpClass``` method in the ```SimTestCase``` class. So you should just go ahead and fix up that for now.

**Comment by mulkieran** [comment]
@bgurney-rh There is actually another place where a correction can be made. Instead of setting ```STRATISD``` as a global constant at the top of ```_misc.py``` it should be set in the one place where it is actually used, ```Service::setup```. And instead of using ```sys.exit``` if the value is not in the environment, it should just raise a ```RuntimeError```.

This way, if the enviroment variable is not set, the module will still be succesfully loaded and only the tests that need to start stratisd will have an error.

**Comment by mulkieran** [comment]
For a solution to the other problems I'm thinking of three RUNNER methods:

* _RUNNER, used by infrastructure which works like RUNNER does now
* SETUP_RUNNER, which catches any exception raised and then reraises that exception chained with a RuntimeError.
* TEST_RUNNER, which catches any exception raised and then reraises that exceptin chained with some subtype of AssertionError

**Comment by bgurney-rh** [comment]
> @bgurney-rh There is actually another place where a correction can be made. Instead of setting `STRATISD` as a global constant at the top of `_misc.py` it should be set in the one place where it is actually used, `Service::setup`. And instead of using `sys.exit` if the value is not in the environment, it should just raise a `RuntimeError`.
> 
> This way, if the enviroment variable is not set, the module will still be succesfully loaded and only the tests that need to start stratisd will have an error.

Sounds good, though we'll need to rename "_STRATISD" to something else:

```
tests/whitebox/_misc.py:63: [C0103(invalid-name), _Service.setup] Variable name "_STRATISD" doesn't conform to snake_case naming style
```

**Comment by bgurney-rh** [comment]
I decided on "stratisd_var" for now; hopefully that's okay.
