### ISSUE TITLE
Macros should use absolute paths for non-prelude data types

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#118]
Currently we reference data types in macros assuming they've been imported into scope. I've typically seen with Rust that it's a good idea to use the absolute path of a data type from the crate that defines it so that there are no additional dependencies on imports outside of the macro. This helps avoid issues with reconciling imports when a macro invocation is added or removed and makes it so that the developer does not need to debug macro errors.

What are your thoughts @mulkieran?

- [x] https://github.com/stratis-storage/stratisd/issues/1748

**Comment by mulkieran** [comment]
Just putting the stratisd sub-issue in December, rather than the project-wide issue.

**Comment by mulkieran** [comment]
Added devicemapper subissue https://github.com/stratis-storage/devicemapper-rs/issues/522.

**Comment by mulkieran** [comment]
Closed by component issues.
