### ISSUE TITLE
[INFO] Stratis support created for ArchLinux

### ISSUE THREAD

**Issue by cawilliamson** [stratis-storage/project#119]
Hi folks!

This is more just for information in case anyone (like me) is interested in experimenting with Stratis on Arch (because y'know... we have to have all of the latest cool tech! :grinning: )

The packages can be installed from AUR:

https://aur.archlinux.org/packages/stratis-cli
https://aur.archlinux.org/packages/stratisd

The packages weren't created by me initially but I have adapted them to make installation simpler and to add stratis boot support (based on ideas found for others doing similar with Dracut-based initrd distros.) On Arch we have a nice wrapper around all of that stuff so all you need to do to boot from a stratis cluster for Arch is:

1.) Add "stratis systemd" to HOOKS in /etc/mkinitcpio.conf
2.) Remove "udev", "usr" and "resume" from HOOKS in /etc/mkinitcpio.conf
3.) Add "root=/dev/dm-5" to your bootloader config.
4.) Run "mkinitcpio -p linux"  (or replace "linux" with your kernel package name)

That's it! You should now be able to boot from a stratis pool if you wish to! :smile: 

Another benefit to posting this here is that I'm seeking feedback on how to resolve the need for boot=/dev/dm-5 and also to improve the build process for the stratisd-boot process. In the PKGBUILD we've got - I'm basically building without dbus, moving the resulting binary, then re-compiling WITH dbus and moving that binary. It would be much nicer if I could create a different binary name for the *without* dbus version (which we need to init the pool before dbus is up.)

EDIT: To add to this - I did try root=/dev/stratis/pool/rootfs for my particular setup and despite the fact that this existed and was a symlink to /dev/dm-5 - it would not work as a boot parameter for me - does boot= not support a symlink to a real device?

Any feedback and/or guidance here would be awesome!

**Comment by mulkieran** [comment]
@shibumi: Thanks for the update! It's also nice to see that ArchLinux is picking up our new versions so promptly.
