### ISSUE TITLE
Drop support for devicemapper tests on Jenkins

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#133]
They just duplicate what we can already do on Travis.

**Comment by mulkieran** [comment]
See https://github.com/stratis-storage/devicemapper-rs/pull/530.

**Comment by bgurney-rh** [comment]
I successfully tested stratis-storage/devicemapper-rs#531 being submitted with the Jenkins test disabled.

**Comment by mulkieran** [comment]
@bgurney-rh Can this be closed now or is there outstanding work within Jenkins that you still need to do?

**Comment by bgurney-rh** [comment]
Yes, this can be closed now.  I've merged the removal of the devicemapper-rs test from the ci repo, and the corresponding test in Jenkins has been disabled for 4 days.

**Comment by mulkieran** [comment]
Great!
