### ISSUE TITLE
No dbus available in emergency mode

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/project#136]
If for example you fail to locate a file system by UUID in `/etc/fstab` you get placed into emergency mode.  You can then supply a root password for maintenance mode or Control-D to continue.  If you go into maintenance mode, dbus is **not available**.  Thus we cannot start up the stratisd process to interact with stratisd configuration.  The python runtime is available as we have pivoted to root fs.

This limitation may hamper corrective actions for Stratis users encountering errors in configuration at boot.

**Comment by mulkieran** [comment]
This is obsoleted by work being done here: https://github.com/stratis-storage/stratisd/pull/2339.
