### ISSUE TITLE
Propose a research project about effectiveness of Rust projects in contrast with C or Python projects

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#138]
They seem to have made the process harder than it used to be, which is probably a good thing:
http://www.bu.edu/rhcollab/get-involved/#propose-research.

**Comment by mulkieran** [comment]
Submitted a proposal today.

**Comment by drckeefe** [comment]
understood

**Comment by mulkieran** [comment]
They went back to making it an easier process....

**Comment by mulkieran** [comment]
And it is in progress...

**Comment by mulkieran** [comment]
This doesn't need to be on any board since it's not tied to our regular cycle.

**Comment by mulkieran** [comment]
The Research Group is in progress, we can retire this issue.
