### ISSUE TITLE
Set up Jenkins and Travis CI so they can be run with libcryptsetup bindings compiled

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#141]
Please look at the errors associated with this PR: https://github.com/stratis-storage/stratisd/pull/1815.

**Comment by mulkieran** [comment]
@jbaublitz Please take a look at the Travis failures first: https://travis-ci.org/stratis-storage/stratisd/jobs/649453166?utm_medium=notification&utm_source=github_status. These look like they may be caused by some error in the Rust bindings.

**Comment by mulkieran** [comment]
@jbaublitz You might want to concentrate on the errors in https://github.com/stratis-storage/libcryptsetup-rs/pull/4, which is a pull just against libcryptsetup. The Travis checks are failing in the identical way there.

**Comment by jbaublitz** [comment]
Given that it is finding some of the methods and not others, this is most likely not a build path issue. If it found none of them, I would be more inclined to think that. Instead it's failing to find more recent methods so I'm going to verify the libcryptsetup verison.

**Comment by mulkieran** [comment]
That makes sense. I'm going to try using the newer, non-default Travis build environment, bionic, which has a much newer version of libcryptsetup, and see what that does.

**Comment by jbaublitz** [comment]
Travis has cryptsetup-1.6.6 currently by default. This indeed seems like the problem.

**Comment by mulkieran** [comment]
Jenkins part is complete!
