### ISSUE TITLE
Figure out a process for giving good karma to new rust packages in Fedora 30

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#143]
The recent Rust upgrade in Fedora 30 was held up by Fedora process. We had the option to give it good karma, and in future, helping it along might be good.

What should our process be? Here are three possible approaches:

1. We can just check a box in the web interface.
2. We can get a Fedora 30 machine and install the package; if it succesfully installs, call it good, and check the box in the web interface or other equivalent action.
3. We can get a Fedora 30 machine, install the package, and build stratisd with it, if that succeeds, call it good, and check the box in the web interface or other equivalent action. To do this, we would also have to install a handful of stratisd's dependencies. But we wouldn't have to worry about cryptsetup requirements, because Fedora 30 already supports a minimal version. But dependencies are clang, ~~libudev-devel~~, dbus-devel, cryptsetup-devel, systemd-devel

Note that even (3) can be done pretty easily just using 1minutetip; I tried it out just now.

Can we use an existing ci script to do this easily?

**Comment by mulkieran** [comment]
@bgurney-rh We'll want to be ready to do this in about two weeks, so I'm moving it into a new slot.

**Comment by mulkieran** [comment]
@bgurney-rh New version of Rust will be coming out next week, so it's probably time to start thinking about this.

**Comment by mulkieran** [comment]
Package has been cut for Fedora 30: https://src.fedoraproject.org/rpms/rust/commits/f30.

**Comment by mulkieran** [comment]
We should do this sometime next week. There was a bit of a problem, when it was discovered that the new compiler couldn't compile itself, but that seems to have been fixed.

**Comment by bgurney-rh** [comment]
I have an idea: if we retrofit the "runalltests.sh" script to use an already-installed rust package, comment out any "rustup" calls (as well as the initial download of the rustup installation script), and install cargo, would that make for a usable test?

I'm trying it now on a Fedora 30 VM, using rust-1.41 in the production repository, to see if the results look usable.

**Comment by mulkieran** [comment]
bodhi link: https://bodhi.fedoraproject.org/updates/FEDORA-2020-85547c8cb1. But bodhi itself seems to be broken; I can't log in without getting a strange error message.

**Comment by mulkieran** [comment]
@bgurney-rh Can you check out the new Rust release? It's available now: https://bodhi.fedoraproject.org/updates/FEDORA-2020-93ed2c4a55.

**Comment by mulkieran** [comment]
I think we have a process that's working, even if it's not fully automatic, so I'm happy to close this.
