### ISSUE TITLE
Checking coverage of unit tests

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#15]
We should sometime figure out how to do this; the only recommeded way seems to be using kcov.

**Comment by mulkieran** [comment]
Somebody is getting code coverage info on their Rust project: https://codecov.io/gh/sagiegurari/cargo-make. Maybe this has gotten easier and we will be able to do it.

**Comment by mulkieran** [comment]
@waltdisgrace Could you add some notes in here indicating what you've found out so far?

**Comment by waltdisgrace** [comment]
Possibilities:
- kcov
- cargo-make
- cargo-tarpaulin
- grcov
- cargo-travis

**Comment by mulkieran** [comment]
This is interesting. We could settle for a coverage report that only runs on Travis as a first step, so maybe cargo-travis is a good thing to look into first.

**Comment by mulkieran** [comment]
We will try with devicemapper and cargo-tarpaulin.

**Comment by mulkieran** [comment]
This is a start! We can close and resume again when we've learned a little more or cargo-tarpaulin becomes more flexible/expressive. It's not surprising that nothing is as advanced as the Python coverage tool yet, but it is a start.
