### ISSUE TITLE
Need to find a way to get libcryptsetup 2.3 running on all our CI

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#152]

**Comment by jbaublitz** [comment]
Github Packages seems like the logical way to host the package. As for generating the deb file, I'll do more research.

**Comment by bgurney-rh** [comment]
As for Fedora 30 test nodes in CI, it's already available, so all I need to do is "dnf update", ideally.

**Comment by jbaublitz** [comment]
@bgurney-rh Now that Travis seems to be able to use our packaged cryptsetup 2.3 successfully, we'll need to update to get Jenkins working again. See stratis-storage/stratisd#1862 for the status of the Travis update.

**Comment by bgurney-rh** [comment]
@jbaublitz Actually, all of the Jenkins tests passed, but I updated the Jenkins test nodes to cryptsetup 2.3.

**Comment by jbaublitz** [comment]
@bgurney-rh stratis-storage/stratisd#1847 is the PR in question. stratis-storage/stratisd#1862 should pass even on 2.2 because it's not using any of the new features in 2.3. Only stratis-storage/stratisd#1847 is using those features currently and that one is failing.

**Comment by bgurney-rh** [comment]
@jbaublitz Ah, that explains it.  I'll re-run the tests on that PR, and hopefully they should pass now.
