### ISSUE TITLE
Tidy up getting Python dependencies in stratisd Jenkins script

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#16]
* Don't get hs-dbus-signature. It's just a Hypothesis strategy for testing the others.

* Get the current versions of the others libraries, not the HEAD of master. Usually this makes little difference because these libraries change so seldom. But, if we did need to do development, then pulling from HEAD would eventually end up breaking something

**Comment by bgurney-rh** [comment]
https://github.com/stratis-storage/stratisd/pull/1498 removes the hs-dbus-signature clone from the stratisd CI test.  (This was merged on April 29, 2019.)

The ci project pull request https://github.com/stratis-storage/ci/pull/2 adds versions of the individual CI tests that checkout the latest tag of the dependencies.  (Should these changes be propagated back to the CI scripts in each project, or will the ci project be the new home for these scripts?)

**Comment by bgurney-rh** [comment]
Both PRs have been merged; we can close this issue now.

**Comment by mulkieran** [comment]
Forgot that we hadn't merged those two PRs yet.

**Comment by mulkieran** [comment]
Closed by https://github.com/stratis-storage/stratisd/pull/1508, https://github.com/stratis-storage/stratis-cli/pull/264.
