### ISSUE TITLE
Look at sos-reports for stratis and see if there is anything that should be added or removed

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#172]
It might be reasonable to try to make use of something in the new reports interface.

**Comment by drckeefe** [comment]
Looking at what sosreport collects today, we could add the following items

stratis --version  # sosreport collects the daemon version, but not the stratis-cli version
stratis --key <list> # when kernel keyring functionality is added the list keys could be added
stratis --report <name> collecting the reports output when this command is added. 

I don't see anything that we need to remove from the list

Current command list for Stratis: 
./sos_commands/stratis/stratis_pool_list
./sos_commands/stratis/stratis_filesystem_list
./sos_commands/stratis/stratis_blockdev_list
./sos_commands/stratis/stratis_daemon_redundancy
./sos_commands/stratis/stratis_daemon_version
./sos_commands/stratis/journalctl_--no-pager_--unit_stratisd

**Comment by mulkieran** [comment]
There isn't much yet that needs changing, and obviously we'll need to wait until our release lands to put in the new interesting stuff. So, we can push this back until July.

**Comment by mulkieran** [comment]
@drckeefe Might be worth taking a look at this one again...we have had the new release out awhile, so the changes could be made.

**Comment by drckeefe** [comment]
I opened a BZ and a Github issue to include this output in the stratis.py plugin.
https://bugzilla.redhat.com/show_bug.cgi?id=1888012
https://github.com/sosreport/sos/issues/2273

**Comment by drckeefe** [comment]
Output of sosreport collecting new stratis commands output (report engine state report, stratis --version, stratis key list, stratis daemon version)

cd ./sosreport-ci-vm-testStratis-2020-10-20-fotcmlj/sos_commands/stratis
ls -trlh
total 44K
-rw-r--r--. 1 root root 3.7K Oct 20 16:03 systemctl_status_stratisd
-rw-r--r--. 1 root root  102 Oct 20 16:03 stratis_pool_list
-rw-r--r--. 1 root root  200 Oct 20 16:03 stratis_filesystem_list
-rw-r--r--. 1 root root   94 Oct 20 16:03 stratis_blockdev_list
-rw-r--r--. 1 root root   32 Oct 20 16:03 stratis_key_list
-rw-r--r--. 1 root root    8 Oct 20 16:03 stratis_daemon_redundancy
-rw-r--r--. 1 root root    6 Oct 20 16:03 stratis_daemon_version
-rw-r--r--. 1 root root    6 Oct 20 16:03 stratis_--version
-rw-r--r--. 1 root root  637 Oct 20 16:03 stratis_report_engine_state_report
-rw-r--r--. 1 root root 4.5K Oct 20 16:03 journalctl_--no-pager_--unit_stratisd
# cat stratis_report_engine_state_report
{
    "errored_pools": [],
    "hopeless_devices": [],
    "pools": [
        {
            "blockdevs": {
                "cachedevs": [],
                "datadevs": [
                    {
                        "path": "/dev/loop1",
                        "uuid": "a08e20e8d8d24cf1958e0f2a8148ccb1"
                    }
                ]
            },
            "filesystems": [
                {
                    "name": "fs1",
                    "uuid": "4a320661fbde42a6aafb3bd0765b23e1"
                }
            ],
            "name": "p1",
            "uuid": "ae064f72156b43e697d39fecce58a935"
        }
    ]
}
# cat stratis_--version
2.1.1
# cat stratis_key_list
Key Description
foo            
# cat stratis_daemon_version
2.1.0

**Comment by mulkieran** [comment]
PR was merged, we can consider this closed.
