### ISSUE TITLE
Tidy up infrastructure for small Python libraries

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#173]
We can background this task, and try to do it as we manage other things wrt. the libraries. EDIT: We will have to manage also moving up to Fedora 31 Python defaults and fixing any lints. See https://github.com/stratis-storage/dbus-python-client-gen/pull/45 for an example of moving default versions.

**Comment by mulkieran** [comment]
Our stratis-cli, devicemapper-rs, stratisd, and libcryptsetup-rs Travis configuration files are now all correctly formatted YAML, and even have a Travis task to verify that they are correctly formatted. We should do that for our other smaller libraries as well.

**Comment by mulkieran** [comment]
See https://github.com/stratis-storage/stratis-cli/pull/538 for an example of what is involved. You can also consult with @bgurney-rh, who did this task for all our more active projects.

**Comment by waltdisgrace** [comment]
@mulkieran 
The smaller Python libraries that I've identified as needing work are: 

- hs-dbus-signature 
- dbus-python-client-gen 
- dbus-client-gen 
- into-dbus-python 
- dbus-signature-pyparsing

So that we're on the same page, does this seem correct?

**Comment by mulkieran** [comment]
> @mulkieran
> The smaller Python libraries that I've identified as needing work are:
> 
>     * hs-dbus-signature
> 
>     * dbus-python-client-gen
> 
>     * dbus-client-gen
> 
>     * into-dbus-python
> 
>     * dbus-signature-pyparsing
> 
> 
> So that we're on the same page, does this seem correct?

Looks right to me.

**Comment by mulkieran** [comment]
@waltdisgrace You will have to revise the attached PRs. You'll need to precede the yamllint commit with commits that upgrade to Fedora 31 defaults for Python and that fix any lints that have been introduced in newer versions of pylint.

**Comment by mulkieran** [comment]
And before any of these ones can be completed, we need to grow through and fix the ones already committed analogously to https://github.com/stratis-storage/stratis-cli/pull/616.

**Comment by mulkieran** [comment]
Superceded by #198 and #199.

**Comment by mulkieran** [comment]
Resolved by merged PRs.
