### ISSUE TITLE
Ensure that D-Bus API booleans indicate Option types

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#186]
This affects two repos:
`stratis-docs`: Update the D-Bus API document.
`stratisd`: Make sure we follow this pattern consistently in our API code.

**Comment by jbaublitz** [comment]
I'll be looking at this shortly.

**Comment by jbaublitz** [comment]
@mulkieran I did have a question if we're considering the changes bugs or a change in the API? I can definitely see an argument for considering them bugs and it would greatly simply the code changes that I'll need to make.

**Comment by mulkieran** [comment]
We would consider these bug fixes. We make a pretty strong statement about failure of idempotency always being considered a bug, probably in the D-Bus API docs.

**Comment by jbaublitz** [comment]
That's what I figured. I'll go ahead with that in mind.

**Comment by mulkieran** [comment]
@jbaublitz We have a separate issue for stratis-docs, so I'm going to close this.
