### ISSUE TITLE
stratisd should be able to recover from an expired key in the keyring

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#196]
Currently, it appears that if an expired key is attached to the session keyring, key operations such as adding a new key fail. This can be resolved by running `keyctl new_session` in the shell.

We should look into two points:
1. Does this behavior happen when stratisd is running under systemd as opposed to from a terminal?
2. If so, should we handle refreshing the session from stratisd if a session keyring gets into a bad state? This is doable with a small amount of additional code. This does not clear the persistent keyring so no keys that have not expired will be cleared.

**Comment by jbaublitz** [comment]
@mulkieran @drckeefe I've done more reading and it appears that it has nothing to do with keys expiring in the persistent keyring. It is the session keyring itself that is expiring and given that it is linked to PAM authentication, this may partially be due to the interaction between PAM and tmux. I'm going to do some experiments with stratisd running as a daemon and report back. The initial test of setting a key expiration to 1 second did not reproduce the problem and it appears that `/proc/keys` is actually reporting expiration of the session keyring.

**Comment by jbaublitz** [comment]
Further investigation into this seems to indicate the following:
* Only system-wide persistent keyring timeouts can be set using `/proc/sys/kernel/keys/persistent_keyring_expiry`. We probably shouldn't allow users to set a system-wide default through Stratis so we can't really change what the expiration time is.
* Once the persistent keyring expires, the new persistent keyring that's attached works perfectly fine with stratisd key listing (no keys are listed as the new persistent keyring is now empty).
* The expired session keyring indeed seems to be a problem with ssh creating a session, tmux inheriting that session and running in the background, and then ssh closing that session. Every new bash instance under tmux inherits the old session ID which seems to confuse the keyring and as a result, the session keyring is determined to be expired.
* Each access of the persistent keyring resets the expiration timer.

I still think there's some value in displaying the expiration for all of the keys so that users are not confused if their keys eventually disappear after the system-wide default of 2 days without use.

**Comment by mulkieran** [comment]
@jbaublitz Will all the Stratis keys share the same expiration time since they are in the persistent keyring?

**Comment by jbaublitz** [comment]
@mulkieran Yes, they will. They are all marked "permanent" and it is the persistent keyring that has the expiration time attached.

**Comment by jbaublitz** [comment]
I think this is irrelevant now. stratisd will only bump into this issue in the very particular situation of using ssh with tmux. Closing.
