### ISSUE TITLE
Script for migrating symlinks

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#203]
We should provide such a script to run once https://github.com/stratis-storage/stratisd/pull/2101 has landed. This is the outline:

* Check preconditions. The script should only take action if:
  * /stratis exists, otherwise there's nothing to do
  * the version of stratisd that is obtained is greater than or equal to the version that maintains symlinks in /dev/stratis AND the udev rule that correctly updates symlinks is in place. We might not need to directly check the existence of the udev rule as later steps might be able to identify by the effects whether it was there or not.

* Perhaps issue a warning about what it does and does not do. If somebody is using the old format symlinks in some context that the script does not know about, it will not do any updates thereto.

* For each link in /stratis with structure ```/stratis/<poolname>/<filesystemname>```:
  * Send a synthetic change event. This should cause the new symlink to be created.

* Run a check, to be determined, to verify that the actions in the previous step have been effected.

* Delete /stratis and all its contents.

It is fine to start out with a partial script that only does steps up to generating the synthetic change events.

Ideally this script should work in a variety of situations. The one where it should cause most actions to occur is if old version of stratisd were running and pools were up. Then the old version of stratisd was brought down, the new version was installed, and brought up. Another situation would be where, on a reboot, a new version of stratisd came up. In that case it should establish all correct symlinks; but old symlinks might still be hanging around in an old /stratis directory.

**Comment by mulkieran** [comment]
In standup, we decided that using ```stratisd -V``` rather than checking the version over the D-Bus ought to work. We believe that, even if stratisd is running, ```stratisd -V``` will complete w/out error. But, maybe we should also check for the presence of the udev script and the rule as well.

We also believe that it is best to make this a shell script.

**Comment by mulkieran** [comment]
The algorithm we're thinking of is maybe a bit less busy:

* for each link ```old_link``` in /stratis:
    * if there is a corresponding ```new_link``` in /dev/stratis and ```old_link``` and ```new_link``` resolve to the same device:
        * do nothing
    * else generate a synthetic change event for the device at ```old_link```
    * remove ```old_link```

* remove /stratis and all its subdirectories

something like that.

**Comment by mulkieran** [comment]
I'll hold this open a little while longer, to track testing.

**Comment by bgurney-rh** [comment]
Test: after upgrading to udev-enabled stratisd and starting stratisd, execute "stratis fs destroy" on the test pool prior to running the symlink migration script.

Result: the symlink in `/stratis` (which was dead because the link target didn't exist anymore, since the filesystem was destroyed) was deleted, which is correct behavior.

**Comment by mulkieran** [comment]
> Test: after upgrading to udev-enabled stratisd and starting stratisd, execute "stratis fs destroy" on the test pool prior to running the symlink migration script.
> 
> Result: the symlink in `/stratis` (which was dead because the link target didn't exist anymore, since the filesystem was destroyed) was deleted, which is correct behavior.

@bgurney-rh: Since the ```if [ -h $i ] && [ -b $i ]``` was false the symlink was not deleted until /stratis was deleted in the last line?

**Comment by mulkieran** [comment]
This is now out in the world. If other things come up we can follow them up in separate issues.
