### ISSUE TITLE
Streamline karma check

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#204]
We should find a way to streamline this check. We do not actually have to package stratisd to check that it can be compiled by the new version of Rust that is available via the testing repo for f31. I think the essentials are just:

1. Get a Fedora 31 machine.
2. Check out new version of rust from testing repo.
3. Check out HEAD of current branch of stratisd.
4. Verify that stratisd compiles with the testing version of rust.
5. Verify that stratisd passes tests, also.

One motivation for this is that we want to decouple this karma test from necessary changes that we might want to make in the spec file that we use for testing.

**Comment by bgurney-rh** [comment]
One challenge that will need to get resolved: the stratisd tests are built for rustup-provided Rust.

**Comment by mulkieran** [comment]
We discussed a way to adapt the test scripts to that they don't automatically assume the presence of rustup and then use it. We believe in this way it will be easy to make a staging script that will install the version of Rust from the testing repo, and then invoke one of our regular test scripts, but run the version of rust we want, i.e., not override with a version from rustup.

**Comment by mulkieran** [comment]
Closed by merged commit.
