### ISSUE TITLE
TPM2 support for encryption keys storing

### ISSUE THREAD

**Issue by alexminder** [stratis-storage/project#207]
Please, add support for storing encryption keys in TPM2 devices. There are 2 ways available for this right now:
- Clevis have TPM2 support;
- cryptsetup native (future release) https://gitlab.com/cryptsetup/cryptsetup/-/merge_requests/51 . I think it is preferred way.

Motivation: Many modern laptops/desktops/servers have TPM2 devices and store encryption keys in secure place is very important for Trusted Boot when kernel have trusted signature for SecureBoot . While boot process TPM registers fills up with correct hashes what protects kernel/BIOS modification.

**Comment by mulkieran** [comment]
We had a bit of a discussion about this: Clevis supports both NBDE and TPM2, and so TPM2 support could be implemented via Clevis. However, via Clevis interface it is always necessary to already have a key, which means that if implemented via Clevis TMP2 could not be the primary encryption mechanism, but if implemented natively via cryptsetup it could be.

**Comment by mulkieran** [comment]
We expect to be implementing TPM support via Clevis: https://github.com/stratis-storage/project/issues/192.

**Comment by mulkieran** [comment]
Closing this, but leaving #192 open until any last changes are merged. TPM2 support via Clevis will appear in next release.
