### ISSUE TITLE
Stress test in the presence of many filesystems

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#208]
How does udev perform when many filesystems are set up? The udev script must wait until there is a D-Bus connection to be able to translate the UUIDs to the names for the symlinks. If many thin devices come up at once will there be a failure to properly construct all the symlinks?

**Comment by bgurney-rh** [comment]
One potential test idea I had: create a pool with 100 filesystems.  With the pool and filesystem devices present (as `/dev/dm-*` devices), remove the symlinks in `/dev/stratis/<poolname>`

Then run this:
```
time for j in $(ls -d /sys/class/block/dm-*); do udevadm test --action=change $j; done
```

This command should re-create the links in `/dev/stratis/<poolname>`, and the time to run this loop will be displayed.

When I tried it on my test system, I see a time of 2.323 seconds.

**Comment by mulkieran** [comment]
Closing this in favor of: https://github.com/stratis-storage/stratisd/issues/2220.
