### ISSUE TITLE
Rust 1.45.2 release steps

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#211]
This is a bug fix release that has come out. We should:

Now:
- [x] Obtain karma information for the new release: https://bodhi.fedoraproject.org/updates/FEDORA-2020-7934563409

Later, possibly:
- [ ] Possibly update recommended development toolchain to 1.45.2
- [ ] Update lowest supported toolchain to 1.45.2

**Comment by mulkieran** [comment]
Assigning to @drckeefe just for karma check.

**Comment by drckeefe** [comment]
stratis-storage/ci/rustadvtest.sh passed on F31

**Comment by mulkieran** [comment]
We won't do any more of the steps, since we only have two weeks until Rust 1.46 comes out and we have no reason to believe we were affected by any of the bugs.
