### ISSUE TITLE
Tracking issue for addition of key description parameter to cryptsetup

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#212]
We hope that this will allow clevis to specify the key description in certain commands that require that the device will be open in order to, e..g,, bind to the device.

https://bugzilla.redhat.com/show_bug.cgi?id=1862173

**Comment by mulkieran** [comment]
@drckeefe Assigning this to you, so that you can keep an eye on the progress of the bz.

**Comment by drckeefe** [comment]
Will our latest work and discussions do we have any more information on this topic?

**Comment by mulkieran** [comment]
Currently in progress on this again.

**Comment by mulkieran** [comment]
We can talk again in August.

**Comment by mulkieran** [comment]
We need to verify that the cryptsetup command-line works; if so we can hand the work off to clevis.

**Comment by mulkieran** [comment]
We have verified that there is still work to be done in cryptsetup.

**Comment by mulkieran** [comment]
Work in cryptsetup has commenced.

**Comment by mulkieran** [comment]
Work in cryptsetup is available for preliminary review.

**Comment by mulkieran** [comment]
Work in Clevis is available for preliminary review.

**Comment by mulkieran** [comment]
cryptsetup changes will be available in 2.6.0

**Comment by mulkieran** [comment]
cryptsetup 2.6.0 is in rawhide only. If we were to take advantage of these changes now, we would only be able to release stratisd in rawhide. The related Clevis PR is https://github.com/latchset/clevis/pull/392 .

**Comment by mulkieran** [comment]
Plan for managing difference between Fedora requirements for releasing Rust programs, and Fedora requirements for everything else. Note that cryptsetup 2.6.1 is being released as far back as f37, which means that only f36, which will be EOL in May, is any different.

1. In the upcoming stratisd release 3.5.3 (or in 3.5.4 depending on timing) we will release the changes that we need to make use of the new clevis option The largest amount of that will be removing code, but of course we'll add some code to use the new option.
2. We enforce dependency on clevis already via "Recommends" in the stratisd spec file. We will drop the version requirement, since clevis v19 is being released all the way back to f36, so specifying the version of clevis is unnecessary.
3. We will release stratisd in Fedora differently in F37/F38/rawhide and in F36.
  a. f37/f38/rawhide will be just as usual
  b. for f36 we have two choices.
    * We can simply not release stratisd in f36 at all. If we choose that path, then it is possible that we will not need to do anything further, but there might be some situations where we have to release compatibility Rust library packages..
    * Make Fedora patches that restore the functionality that was removed in Step (1).
