### ISSUE TITLE
Would like to eliminate junky-looking HTML in Jenkins title

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#22]

**Comment by bgurney-rh** [comment]
It looks like it's posting the HTML of a hyperlink to the pull request, with the PR's title as the "TITLE" tag contents, and the URL to the PR as the "HREF" contents.

However, most of the time, the hyperlink is too long, and is ellipsized, and it's not rendering as HTML in this specific view.

**Comment by mulkieran** [comment]
Looks like this is in progress, so I'll put it back in May.

**Comment by bgurney-rh** [comment]
The "Build description template" for the jobs handling the devicemapper-rs, stratis-cli, and stratisd repositories has been changed to the following:
```
PR #$pullId: $title -- $url
```

This will result in the build history's abbreviated description looking like this, for an example PR that I created:
```
PR ​#283: ​blackbox: ​update ​README ​stratis_cert.py ​example ​block ​devices ​--... 
```

The page for that specific build will have the pull request URL.
