### ISSUE TITLE
Add clevis and clevis-luks packages to CI

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#227]
The tests on stratis-storage/stratisd#2211 are failing because the necessary executables are not found on the test systems. The packages `clevis` and `clevis-luks` should provide all of the executables needed.

**Comment by mulkieran** [comment]
Likely this will also require changes in the ci repo, to update dependencies script w/ these additional dependencies.

**Comment by bgurney-rh** [comment]
The packages have been added in CI, and the existing testing CI nodes have had the clevis and clevis-luks packages installed.
