### ISSUE TITLE
Try replacing Travis with Github Actions

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#228]
Stages:
- [x] Put up a PR to use Github Actions and Travis side by side.
- [x] ~~Test both for a period of time and see if they are consistent.~~
- [x] Remove Travis.

**Comment by mulkieran** [comment]
@jbaublitz Could you give this a higher priority, now that Travis CI builds are taking all night to complete?

**Comment by mulkieran** [comment]
Since we moved to travis-ci.com things are better, so we dropped the priority. However, we still have reasons to make the move, and it turns out that Hypothesis has made the move: https://github.com/HypothesisWorks/hypothesis/pull/2674#issuecomment-731720966.

**Comment by jbaublitz** [comment]
@mulkieran Are there any repos still using Travis? If there aren't, I'm going to disable Travis on our organization.

**Comment by mulkieran** [comment]
Still quite a few...I'm working through those little libraries 1-by-1.

**Comment by jbaublitz** [comment]
Okay, just let me know when you're ready.

**Comment by mulkieran** [comment]
We should no longer have any connection with Travis CI.
