### ISSUE TITLE
Traceback when setting key in console

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/project#233]
OS: Fedora 33 (server)
Version: 
stratis-cli-2.1.1-2.fc33.noarch
stratisd-2.1.0-3.fc33.x86_64

How to reproduce:
From the console of a virtual machine (or a physical machine) attempt to set a key in stratis.

```
# stratis key set --capture-key testkey
 
stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below.
 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 319, in dbus_func
    return dbus_method(*xformed_args, timeout=timeout)
  File "/user/lib64/python3.9/site-package/dbus/proxies.py", line 141, in _call_
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.9/site-packages/dbus/connections.py", line 652, in call_blocking
    reply_message = self.end_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Disconnected: Connections was disconnected before a reply was received
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
    func(*args)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 679, in set_key
    ((changed, existing_modified), return_code, message) = _add_update_key(
  File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 210, in _add_update_key
    terminal_attributes = tcgetattr(file_desc)
termios.error: (25, 'Inappropriate ioctl for device')
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/usr/bin/stratis", line 35, in <module>
    main()
  File "/usr/bin/stratis", line 32, in main
    return run()(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 65, in the_func
    handle_error(err)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_error_reporting.py", line 289, in handle_error
    raise err
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 60, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['key', 'set', '--capture-key', 'testkey'] which were parsed to Namespace(propagate=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f7d6b6b4940>, keydesc='testkey', keyfile_path=None, capture_key=True) failed
```

Workaround: 
Use a terminal or use the option --keyfile-path instead of --capture-key when setting a key

**Comment by mulkieran** [comment]
@mulkieran Will address the stack trace.
@jbaublitz, @drckeefe Will try to find a shareable reproducer.

**Comment by mulkieran** [comment]
On Stratis 2.2, the expected happens and the daemon returns the same error, "Inappropriate ioctl for device (os error 2)"

```
    stratis key set --capture-key testkey
    Execution failed:
    Stratisd failed to perform the operation that you requested.  It returned the following information via the D-Bus: ERROR: IO error: Inappropriate ioctl for device (os error 25)
     
    stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below.
     
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 319, in dbus_func
        return dbus_method(*xformed_args, timeout=timeout)
      File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
        return self._connection.call_blocking(self._named_service,
      File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
        reply_message = self.send_message_with_reply_and_block(
    dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Disconnected: Connection was disconnected before a reply was received
     
    The above exception was the direct cause of the following exception:
     
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 43, in the_func
        result.func(result)
      File "/usr/lib/python3.9/site-packages/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
        func(*args)
      File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 675, in set_key
        ((changed, existing_modified), return_code, message) = _add_update_key(
      File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 214, in _add_update_key
        add_ret = Manager.Methods.SetKey(
      File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 325, in dbus_func
        raise DPClientInvocationError(err_msg, interface_name,
    dbus_python_client_gen._errors.DPClientInvocationError: Error while invoking method "SetKey" belonging to interface "org.storage.stratis2.Manager.r2" with arguments (testkey, <dbus.UnixFd object at 0x7fb7c59324b0>, 1)
     
    The above exception was the direct cause of the following exception:
     
    Traceback (most recent call last):
      File "/usr/bin/stratis", line 35, in <module>
        main()
      File "/usr/bin/stratis", line 32, in main
        return run()(sys.argv[1:])
      File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 65, in the_func
        handle_error(err)
      File "/usr/lib/python3.9/site-packages/stratis_cli/_error_reporting.py", line 289, in handle_error
        raise err
      File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 60, in the_func
        raise StratisCliActionError(command_line_args, result) from err
    stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['key', 'set', '--capture-key', 'testkey'] which were parsed to Namespace(propagate=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7fb7c5be98b0>, keydesc='testkey', keyfile_path=None, capture_key=True) failed
```

**Comment by mulkieran** [comment]
However, there is some work to be done by me, probably. The error "org.freedesktop.DBus.Error.Disconnected" is not one we currently capture when error reporting, and we probably should. But I'll defer worrying about that until investigation is complete.

**Comment by mulkieran** [comment]
Well file a bug against the appropriate dbus-related entity, and I'll pick up the work on the stack trace.

**Comment by mulkieran** [comment]
Bug filed: https://gitlab.freedesktop.org/dbus/dbus/-/issues/313

**Comment by drckeefe** [comment]
It would seem that selinux is getting in the way here.   If I disable selinux (setenforce 0) on the console I don't see this issue.  @jbaublitz can you try to reproduce?

**Comment by mulkieran** [comment]
@drckeefe The output that you put in a pastebin and that I copied into this bug in https://github.com/stratis-storage/project/issues/233#issuecomment-717544087 can't be quite right. It must show the result of two commands, rather than one, as the phrase "Execution failed" and the phrase "stratis encountered an unexpected error" are mutually exclusive in a single run of the CLI. Can you redo your Stratis 2.2.0 test and report the output here?

**Comment by drckeefe** [comment]
@mulkieran Here is the output you requested:

stratis key set testkey1 --capture-key 
Enter desired key data followed by the return key:
stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below. 

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 319, in dbus_func
    return dbus_method(*xformed_args, timeout=timeout)
  File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Disconnected: Connection was disconnected before a reply was received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
    func(*args)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 675, in set_key
    ((changed, existing_modified), return_code, message) = _add_update_key(
  File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 214, in _add_update_key
    add_ret = Manager.Methods.SetKey(
  File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 325, in dbus_func
    raise DPClientInvocationError(err_msg, interface_name,
dbus_python_client_gen._errors.DPClientInvocationError: Error while invoking method "SetKey" belonging to interface "org.storage.stratis2.Manager.r2" with arguments (testkey1, <dbus.UnixFd object at 0x7f724a5df4d0>, 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/stratis", line 35, in <module>
    main()
  File "/usr/bin/stratis", line 32, in main
    return run()(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 65, in the_func
    handle_error(err)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_error_reporting.py", line 289, in handle_error
    raise err
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 60, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['key', 'set', 'testkey1', '--capture-key'] which were parsed to Namespace(propagate=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f724a8948b0>, keydesc='testkey1', keyfile_path=None, capture_key=True) failed

**Comment by mulkieran** [comment]
> @mulkieran Here is the output you requested:
> 
> ```
> stratis key set testkey1 --capture-key 
> Enter desired key data followed by the return key:
> stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below. 
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 319, in dbus_func
>     return dbus_method(*xformed_args, timeout=timeout)
>   File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
>     return self._connection.call_blocking(self._named_service,
>   File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
>     reply_message = self.send_message_with_reply_and_block(
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Disconnected: Connection was disconnected before a reply was received
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 43, in the_func
>     result.func(result)
>   File "/usr/lib/python3.9/site-packages/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
>     func(*args)
>   File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 675, in set_key
>     ((changed, existing_modified), return_code, message) = _add_update_key(
>   File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 214, in _add_update_key
>     add_ret = Manager.Methods.SetKey(
>   File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 325, in dbus_func
>     raise DPClientInvocationError(err_msg, interface_name,
> dbus_python_client_gen._errors.DPClientInvocationError: Error while invoking method "SetKey" belonging to interface "org.storage.stratis2.Manager.r2" with arguments (testkey1, <dbus.UnixFd object at 0x7f724a5df4d0>, 1)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/bin/stratis", line 35, in <module>
>     main()
>   File "/usr/bin/stratis", line 32, in main
>     return run()(sys.argv[1:])
>   File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 65, in the_func
>     handle_error(err)
>   File "/usr/lib/python3.9/site-packages/stratis_cli/_error_reporting.py", line 289, in handle_error
>     raise err
>   File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 60, in the_func
>     raise StratisCliActionError(command_line_args, result) from err
> stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['key', 'set', 'testkey1', '--capture-key'] which were parsed to Namespace(propagate=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f724a8948b0>, keydesc='testkey1', keyfile_path=None, capture_key=True) failed
> ```

Ok!

**Comment by leseb** [comment]
FYI:

```
Nov 21 16:22:09 localhost.localdomain audit[704]: AVC avc:  denied  { read } for  pid=704 comm="dbus-broker" path="pipe:[141146]" dev="pipefs" ino=141146 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=unconfined_u:system_r:spc_t:s0 tclass=fifo_file permissive=0
```

In case someone wants to write the rule...

Does this mean the recommendation is to disable SELinux to add a key with stratis-cli? Thanks.

**Comment by mulkieran** [comment]
> FYI:
> 
> ```
> Nov 21 16:22:09 localhost.localdomain audit[704]: AVC avc:  denied  { read } for  pid=704 comm="dbus-broker" path="pipe:[141146]" dev="pipefs" ino=141146 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=unconfined_u:system_r:spc_t:s0 tclass=fifo_file permissive=0
> ```
> 
> In case someone wants to write the rule...
> 
> Does this mean the recommendation is to disable SELinux to add a key with stratis-cli? Thanks.

No, although that should work ;)  But we have had previous instances where SELinux rules have inhibited certain stratis actions. If you file a separate bug we can see about following up this failure. Is it the exact same cause...setting a key in the keyring?

**Comment by leseb** [comment]
> > FYI:
> > ```
> > Nov 21 16:22:09 localhost.localdomain audit[704]: AVC avc:  denied  { read } for  pid=704 comm="dbus-broker" path="pipe:[141146]" dev="pipefs" ino=141146 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=unconfined_u:system_r:spc_t:s0 tclass=fifo_file permissive=0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In case someone wants to write the rule...
> > Does this mean the recommendation is to disable SELinux to add a key with stratis-cli? Thanks.
> 
> No, although that should work ;) But we have had previous instances where SELinux rules have inhibited certain stratis actions. If you file a separate bug we can see about following up this failure. Is it the exact same cause...setting a key in the keyring?

Yes, it's the same command execution, will open a new issue or re-use this one since it's the same command execution. Up to you.

**Comment by mulkieran** [comment]
> > > FYI:
> > > ```
> > > Nov 21 16:22:09 localhost.localdomain audit[704]: AVC avc:  denied  { read } for  pid=704 comm="dbus-broker" path="pipe:[141146]" dev="pipefs" ino=141146 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=unconfined_u:system_r:spc_t:s0 tclass=fifo_file permissive=0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In case someone wants to write the rule...
> > > Does this mean the recommendation is to disable SELinux to add a key with stratis-cli? Thanks.
> > 
> > 
> > No, although that should work ;) But we have had previous instances where SELinux rules have inhibited certain stratis actions. If you file a separate bug we can see about following up this failure. Is it the exact same cause...setting a key in the keyring?
> 
> Yes, it's the same command execution, will open a new issue or re-use this one since it's the same command execution. Up to you.

Better open a new one...this is a regression in the rules, as far as I can tell.

**Comment by jbaublitz** [comment]
@mulkieran Just to be clear, I don't think this is related to the previous key setting error at all looking at the error. That was related to the console file descriptor being passed as I understood it, and the SELinux error looked different from what I remember. 

@leseb When does this problem manifest? What command are you running? Is this related to the issue you were referring to about the D-Bus IDs needing to be identical or is this a different problem?

**Comment by mulkieran** [comment]
> > > > FYI:
> > > > ```
> > > > Nov 21 16:22:09 localhost.localdomain audit[704]: AVC avc:  denied  { read } for  pid=704 comm="dbus-broker" path="pipe:[141146]" dev="pipefs" ino=141146 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=unconfined_u:system_r:spc_t:s0 tclass=fifo_file permissive=0
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > In case someone wants to write the rule...
> > > > Does this mean the recommendation is to disable SELinux to add a key with stratis-cli? Thanks.
> > > 
> > > 
> > > No, although that should work ;) But we have had previous instances where SELinux rules have inhibited certain stratis actions. If you file a separate bug we can see about following up this failure. Is it the exact same cause...setting a key in the keyring?
> > 
> > 
> > Yes, it's the same command execution, will open a new issue or re-use this one since it's the same command execution. Up to you.
> 
> Better open a new one...this is a regression in the rules, as far as I can tell.

@leseb Yes. Please open a new issue. It looks like this is a new kind of SELinux failure, even if it is on the same command, so we'll need all the context you can give us.

**Comment by leseb** [comment]
After further investigation, this is not a stratis-cli issue but most likely a missing SeLinux rule when running the client in a container. It's tracked here: https://github.com/containers/container-selinux/issues/197.
The command works when not ran in a container and in container when I apply the rule described in the issue.

Thanks!
