### ISSUE TITLE
Rust 1.48 Release Steps

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#241]
- [x] Fix all stable clippy failures
- [x] ~~karma for new Fedora release: https://bodhi.fedoraproject.org/updates/FEDORA-2020-61c6c940d0~~
- [x] increase recommended development toolchain to 1.48

**Comment by mulkieran** [comment]
The new release should come out tomorrow

**Comment by bgurney-rh** [comment]
Stable is now 1.48.0.

There are no clippy errors in devicemapper-rs or libcryptsetup-rs.

**Comment by mulkieran** [comment]
@bgurney-rh For stratisd you can edit the Makefile to ignore the map_err_ignore clippy error. I'm sure we made a more or less conscious decision in each case, and it won't be worth the work to try and fix any of the lint-y code individually.

**Comment by bgurney-rh** [comment]
@mulkieran OK; I was fighting with trying to edit `src/stratis/errors.rs`, and wasn't making progress.  (As far as I can tell, we do wrap the error in an enum, but apparently not to the liking of this lint.)

However, both Rust 1.45.0 and 1.47.0 will show the error "unknown lint: 'clippy::map-err-ignore'".

**Comment by bgurney-rh** [comment]
I forgot that, with our updated linting strategy, we won't have to worry about the "unknown lint" errors.
