### ISSUE TITLE
Refine how we handle external command-line dependencies

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#247]
I think that while most of the dependencies that depend on command-line tools have to be viewed as mandatory, some people would prefer that Clevis was not mandatory, and this problem may come up again w/ other command-line tools.

Therefore, we should refine our management of command-line dependencies.

This is a dispersed problem, and somewhat difficult to solve, as it involves both our own source code and downstream packaging.

Ideally, we would solve it by a compilation time mechanism, and that compilation-time mechanisms would be used by downstream packaging.

A compilation time mechanism would compile out the initial checks on startup that stratisd has for the presence of necessary applications. It would also have to conditionally compile in error returns on certain commands that use Clevis, like unlock. It might also simply compile out the bind command entirely. Much code, in e.g., the crypt module would necessarily remain.

Note that this is another problem w/ the command-line tools; if we were depending on a library some parts of this would be more straightforward.

- [x] Make Clevis ependencies within stratisd dynamically checked. Resolved by https://github.com/stratis-storage/stratisd/pull/2398.
- [ ] Update Fedora spec file to have optional clevis dependencies

**Comment by mulkieran** [comment]
We'll want to do this dynamically instead.

**Comment by jbaublitz** [comment]
@mulkieran Does this belong in project? I think it's localized to stratisd.

**Comment by mulkieran** [comment]
I put it in project because we'll also have to adjust spec file.

**Comment by jbaublitz** [comment]
Okay! That makes sense now.

**Comment by mulkieran** [comment]
Expect to be packaging in April.

**Comment by mulkieran** [comment]
I think we should consider this closed by merged PRs as I use changes to the blackbox spec files as my guide to changes that I need to make in Fedora spec file.
