### ISSUE TITLE
Rust 1.49 Release steps

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#252]
- [x] Fix all stable clippy failures
- [x] karma for new Fedora release
- [x] increase recommended development toolchain to 1.49

**Comment by mulkieran** [comment]
But not until January

**Comment by mulkieran** [comment]
@bgurney-rh Rust 1.49 is out, so you can start this whenever you're ready.

**Comment by bgurney-rh** [comment]
There are no failures in libblkid-rs for 1.49.

**Comment by mulkieran** [comment]
Waiting on Fedora release now.

**Comment by mulkieran** [comment]
Upstream bz for Fedora release: https://bugzilla.redhat.com/show_bug.cgi?id=1911868.

**Comment by mulkieran** [comment]
@bgurney-rh , @drckeefe We now have the opportunity to give karma: https://bodhi.fedoraproject.org/updates/FEDORA-2021-e6b4f9b0d2.

**Comment by drckeefe** [comment]
Tested using https://github.com/stratis-storage/ci/blob/master/rustadvtest.sh - added karma

**Comment by mulkieran** [comment]
Waiting for new build to clear.

**Comment by mulkieran** [comment]
@bgurney-rh Looks like you can start the last step anytime.

**Comment by mulkieran** [comment]
Looks good, awaiting libblkid-rs update.

**Comment by mulkieran** [comment]
Resolved by attached PRs.
