### ISSUE TITLE
Explore uses of cargo-vendor-filterer for omitting a variety of undesirable dependencies from vendor tar file

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#265]
https://github.com/rust-lang/cargo/issues/7058

**Comment by cgwalters** [comment]
https://github.com/cgwalters/cargo-vendor-filterer now exists!

**Comment by mulkieran** [comment]
We can edit the stratisd Cargo.toml w/ the correct settings.

**Comment by mulkieran** [comment]
I believe this is done.
