### ISSUE TITLE
Rust 1.50 Release Steps

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#266]
- [x] Fix all stable clippy failures
- [x] karma for new Fedora release: https://bodhi.fedoraproject.org/updates/FEDORA-2021-983c82d40e
- [x] increase recommended development toolchain to 1.50

Coming this Thursday, Feb 11.

**Comment by mulkieran** [comment]
We'ld like to do #258 first.

**Comment by mulkieran** [comment]
Link to bz for Fedora release: https://bugzilla.redhat.com/show_bug.cgi?id=1927914. This might take a little longer than usual.

**Comment by mulkieran** [comment]
@bgurney-rh Can resume work on the clippy part, at least.

**Comment by bgurney-rh** [comment]
Only stratisd appears to have clippy errors right now.  I set up an in-progress PR in stratisd #2402.

**Comment by bgurney-rh** [comment]
One other challenge: "make clippy" for 1.49 reports the following:
```
error[E0602]: unknown lint: `clippy::suspicious_operation_groupings`
```

**Comment by mulkieran** [comment]
We'll wait for new version of rust to be released into Fedora.

**Comment by drckeefe** [comment]
karma added after tests passed

**Comment by mulkieran** [comment]
Ok! It'll probably land in f32 tomorrow.

**Comment by mulkieran** [comment]
Probably tomorrow.

**Comment by mulkieran** [comment]
Today!

**Comment by mulkieran** [comment]
Closed by merged PRs.
