### ISSUE TITLE
Packaging dbus-tree and dbus-tokio for Fedora

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#277]

**Comment by mulkieran** [comment]
https://github.com/diwic/dbus-rs/issues/322

**Comment by mulkieran** [comment]
Once in rawhide, we'll want to get them into f34 as well.

**Comment by mulkieran** [comment]
dbus-tree is in rawhide.

**Comment by mulkieran** [comment]
dbus-tree has been submitted to stable: https://bodhi.fedoraproject.org/updates/FEDORA-2021-44dc793af4.

**Comment by jbaublitz** [comment]
dbus-tokio is in rawhide too.

**Comment by mulkieran** [comment]
Upstream bz for dbus-tokio: https://bugzilla.redhat.com/show_bug.cgi?id=1948149.

**Comment by mulkieran** [comment]
Received a report that dbus-tree was pushed to stable.

**Comment by jbaublitz** [comment]
dbus-tokio is in testing in Fedora 34.

**Comment by mulkieran** [comment]
All packages have landed.
