### ISSUE TITLE
UUIDs for Stratis unencrypted block devices not appearing in /dev/disk/by-uuid

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#288]
It appears that our UUIDs do not get handled properly by udev. The symptom of this problem is that udev provides symlinks under `/dev/disk/by-uuid` for devices that it detects. Unencrypted Stratis devices do not appear in this directory. I also looked into the udev database records for Stratis unencrypted pools and while all other UUIDs are in the dash format, ours are not. My suspicion is that udev requires it to be in this format to function properly.

**Comment by jbaublitz** [comment]
So far what I've determined is that our UUIDs are displayed without dashes. This appears to be unrelated to the problem however. udev rules only generate `/dev/disk/by-uuid` links for a few types of `ID_FS_USAGE` values. Ours is `raid` which is not one of the choices that generates this symlink. To have this symlink generated, our `ID_FS_USAGE` value would have to be `crypto`, `other`, or `filesystem`.

**Comment by mulkieran** [comment]
We've decided to handle this by modifying how an unencrypted root filesystem is set up.

**Comment by mulkieran** [comment]
Actually, let's treat this as the missing UUIDs problem, and write our own rule!

**Comment by mulkieran** [comment]
Superceded by #289
