### ISSUE TITLE
Run Python tasks on Fedora containers, add next version of Fedora tasks to nightly.yaml

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#294]
I'm going to add a Python-specific nightly job for Fedora 33 in GIthub Actions so that @bgurney-rh has advanced notice of what's changed in pylint/black before we update our infrastructure to the next version of Fedora.

**Comment by mulkieran** [comment]
Once we prove that the one in stratisd is doing what we want, it makes sense for @bgurney-rh to pick up the ones for the other repos that use Python. And I can decide what to do about the little libraries, as they are still using tox for all CI, etc.

**Comment by mulkieran** [comment]
Closed by attached PRs.
