### ISSUE TITLE
Set msrv in .clippy.toml

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#306]
If we set msrv, as ```msrv = "1.49.0"``` then lints which observe this value won't suggest fixes that we can't use because our msrv does not support them.

msrv (minimum supported rust version)

**Comment by mulkieran** [comment]
Some docs about .clippy.toml: https://github.com/rust-lang/rust-clippy#configuration.

**Comment by mulkieran** [comment]
Using this would mean that if we bumped our minimum supported version, we might start to see lints that we hadn't seen before using the same version of the linter. I think this is fine.

**Comment by bgurney-rh** [comment]
One thing I discovered: if I have rust 1.49.0 installed (via rustup), I see this error when trying to run "make clippy" in stratisd:
```
error: error reading Clippy's configuration file '... .clippy.toml': unknown field 'msrv'
```

**Comment by mulkieran** [comment]
> One thing I discovered: if I have rust 1.49.0 installed (via rustup), I see this error when trying to run "make clippy" in stratisd:
> 
> ```
> error: error reading Clippy's configuration file '... .clippy.toml': unknown field 'msrv'
> ```

So long as the 1.52.1 version recognizes the msrv key I think that's Ok. We've reached almost a general policy of only running our linter, be it Rust or Python, on our one selected development version.

**Comment by mulkieran** [comment]
Closed by merged PRs.
