### ISSUE TITLE
Can we run the blackbox tests as part of our CI?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#32]
The blackbox tests are, in some sense, our gating tests.

We would like to run them in CI so that when we fix a bug we can modify the tests at the same time.

**Comment by mulkieran** [comment]
@bgurney-rh If we could do this, it would be good. I don't know how extensive the work required would be. These are meant to be run as gating tests, but it is possible that they can also be run more directly in our CI, one way or another.

**Comment by mulkieran** [comment]
@bgurney-rh If we could do this, it would be good. I don't know how extensive the work required would be. If running all of the tests requires a lot of setup, but running a large subset of them requires much less setup, we could perhaps settle for that.

**Comment by mulkieran** [comment]
Let's take another look a this, it's becoming more important as the anticipation of causing tests to fail hinders our development.

**Comment by mulkieran** [comment]
The ultimate plan is to move these tests into a separate repo, so that their version isn't tied to the version of stratis-cli.

**Comment by bgurney-rh** [comment]
If there's a way to use the test devices specified in the "test_config.json" file used in the stratisd test, that would make things a lot easier.

Despite the blackbox tests being in stratis-cli, they require real devices for testing.

**Comment by bgurney-rh** [comment]
I found an issue with the test_config.json file being in the calling user's home directory; that's documented in ci issue #24

**Comment by bgurney-rh** [comment]
ci issue 24 was resolved; the test config file is now in /etc/stratis/test_config.json.

**Comment by bgurney-rh** [comment]
I added a blackbox test runner script, in ci PR 27.

**Comment by mulkieran** [comment]
@bgurney-rh Should we close this now?

**Comment by mulkieran** [comment]
Running, closing!
