### ISSUE TITLE
mv test_config.json.example from stratisd repo to ci repo if it still seems useful

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#345]
If it does not seem useful, just remove it from stratisd entirely. Also, edit ```stratisd/tests/README.md``` so that instead of including instructions for setting up real tests it just links to the appropriate README in the ci repo.

**Comment by bgurney-rh** [comment]
I'm not entirely convinced that the reference to test_config.json is not useful in stratisd.  Those tests do use the file; however, it's far easier to execute the tests on a new system when using the ci scripts (especially with the rustup-installed cargo command, and having to set the environment variables properly in order to find the cargo command).

**Comment by mulkieran** [comment]
@bgurney-rh The things I want to go away are the ```.example``` file and also the duplicate docs: there's some docs that explain how to run the real tests in a stratisd README and some in a ci README.

One thing that you could do instead of my first suggestion:
1. Remove test_config.json.example from stratisd
2. Move tests/README.md which describes the Rust unit tests including the ones on real devices up to the top level, but call it ```README_tests.md```. 
3. Fix up ```README_tests.md``` so it doesn't refer to the ```.example``` file at all, but just describes the format like in ```ci/README.md```.
4. Have ```ci/README.md``` refer to the instructions in ```stratisd/README_tests.md``` for setting up real devices.

I think that the only reason that info about running tests on real and loopbacked devices and the ```.example``` file is in the ```tests``` subdirectory is that stratisd once used "integration tests" that required such a setup. Now we stick to the unit test framework and have for quite a while and there are only Python-based tests in that tests subdirectory. So ```tests/README.md``` and the ```.example``` file are totally out of place there.

**Comment by bgurney-rh** [comment]
OK, now I think I see how to get started.  Hopefully it's heading in the right direction.

**Comment by mulkieran** [comment]
We decided to skip step 4 as not really worth the trouble, so https://github.com/stratis-storage/stratisd/pull/2773 should close this.
