### ISSUE TITLE
libblkid-rs and libblkid-rs-sys releases on Fedora

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#353]

**Comment by mulkieran** [comment]
Bodhi link: https://bodhi.fedoraproject.org/updates/FEDORA-2021-55a95ead70

**Comment by jbaublitz** [comment]
Here is the bodhi link for libblkid-rs: https://bodhi.fedoraproject.org/updates/FEDORA-2021-03dcc09dce

**Comment by mulkieran** [comment]
I believe we should consider this done.
