### ISSUE TITLE
Increase Rust recommended development toolchain to 1.56.1

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#357]
This is a bug fix release, see: https://blog.rust-lang.org/2021/11/01/Rust-1.56.1.html and related links.

I expect that it will land in Fedora pretty promptly.

- [x] Fix any newly introduced compiler or clippy errors
- [x] Give karma for f34 release: https://bodhi.fedoraproject.org/updates/FEDORA-2021-0578e23912
      How to do this:
      * Get the package
      * dnf install ```cargo```, ```clippy```, ```rustfmt```
      * do something like the script below[1]
- [x] Bump current development toolchain in GitHub workflows

[1]
```
for each ${repo_name} in (devicemapper-rs, libcryptsetup-rs, libblkid-rs, stratisd):
  git clone https://github.com/stratis-storage/${repo_name}
  (cd ${rust_repo}; make fmt; make build; make clippy; make test)
 ```

**Comment by bgurney-rh** [comment]
There were no clippy or compiler errors in stratisd, devicemapper-rs, libblkid-rs, or libcryptsetup-rs in my test with Rust 1.56.1.

**Comment by mulkieran** [comment]
Probably karma tomorrow.

**Comment by mulkieran** [comment]
Probably merge all associated PRs tomorrow.

**Comment by mulkieran** [comment]
Resolved by attached PRs.
