### ISSUE TITLE
Increase Rust recommended toolchain to 1.58

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#386]
- [x] Fix any newly introduced compiler or clippy errors
- [x] Give karma for f34 release: https://bodhi.fedoraproject.org/updates/FEDORA-2022-8ad99dbeb5
  Make sure that all our Rust projects can be formatted, built, linted, and lightly tested with the new Rust toolchain.
- [x] Bump current development toolchain in GitHub workflows

**Comment by bgurney-rh** [comment]
Trying to run "make fmt" fails, because the "fmt" subcommand for cargo seems to no longer exist:
```
error: The subcommand 'fmt' wasn't recognized
```

**Comment by bgurney-rh** [comment]
False alarm; I didn't have rustfmt installed.

**Comment by mulkieran** [comment]
Resolved by merged PRs.
