### ISSUE TITLE
Sort imports using isort

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#40]
Unfortunately, neither black nor yapf orders them in any way, unlike rustfmt, which does, but it might make the imports more readable. This is not remotely urgent, though.

**Comment by mulkieran** [comment]
We can use isort to sort our imports, hypothesis does this as well.

**Comment by mulkieran** [comment]
@jbaublitz It looks like we might have a winning configuration. Take a look at the attached PRs. The libraries are small, so the changes are very limited, but so far they check out consistently in Travis with the default version of Python 3.7, which is 3.7.1 and my machine's version which is 3.7.5, as of today.

**Comment by mulkieran** [comment]
I do not believe isort is capable of sorting imports within methods, like our local ```_data``` imports in stratis-cli.

**Comment by jbaublitz** [comment]
@mulkieran I took a look at it and I have one concern. Are we confident that nested imports will work with black with the current multiline output that's selected? Furthermore, why is option 3 for multiline output giving different output from the documentation example? According to the README, 3 should result in something that looks more like:
```
from third_party import (
    lib1,
    lib2,
    lib3,
    lib4,
)
```
which is not what I see in the PR. I'm concerned that this is a brittle solution given that if you run `make fmt`, it appears that isort will be run first and then black which I'm guessing is why the isort option we chose doesn't match up with the example in the README. If we want the same output as the output in the PR currently, we should be using option 7 which looks like:
```
from third_party import lib1, lib2, lib3, ...  # NOQA
```

If option 7 is what we want, my guess is that specifying line length as you did here might have actually fixed the conflict between black and isort that I saw previously (it did appear as if there were two separate conflicting line lengths as defaults in the two different tools).

What are your thoughts?

**Comment by mulkieran** [comment]
> @mulkieran I took a look at it and I have one concern. Are we confident that nested imports will work with black with the current multiline output that's selected? Furthermore, why is option 3 for multiline output giving different output from the documentation example? According to the README, 3 should result in something that looks more like:
> 
> ```
> from third_party import (
>     lib1,
>     lib2,
>     lib3,
>     lib4,
> )
> ```

That's only if the output would actually take up multiple lines. We don't import enough things in
either of these libraries to have more imports than would fit in a single line. I experimented a
little with a PR for stratis-cli, where there are enough imports from a single module to trigger
the multi-line configuration. When there are, something like the example above is generated.

> which is not what I see in the PR. I'm concerned that this is a brittle solution given that if you run `make fmt`, it appears that isort will be run first and then black which I'm guessing is why the isort option we chose doesn't match up with the example in the README. If we want the same output as the output in the PR currently, we should be using option 7 which looks like:
> 
> ```
> from third_party import lib1, lib2, lib3, ...  # NOQA
> ```
> 
> If option 7 is what we want, my guess is that specifying line length as you did here might have actually fixed the conflict between black and isort that I saw previously (it did appear as if there were two separate conflicting line lengths as defaults in the two different tools).
> 
> What are your thoughts?

**Comment by jbaublitz** [comment]
> > @mulkieran I took a look at it and I have one concern. Are we confident that nested imports will work with black with the current multiline output that's selected? Furthermore, why is option 3 for multiline output giving different output from the documentation example? According to the README, 3 should result in something that looks more like:
> > ```
> > from third_party import (
> >     lib1,
> >     lib2,
> >     lib3,
> >     lib4,
> > )
> > ```
> 
> That's only if the output would actually take up multiple lines. We don't import enough things in
> either of these libraries to have more imports than would fit in a single line. I experimented a
> little with a PR for stratis-cli, where there are enough imports from a single module to trigger
> the multi-line configuration. When there are, something like the example above is generated.
> 

That will be a problem with `black` if I recall correctly. Feel free to verify that, but I'm pretty confident that that broke compatibility between the two tools. We should ensure that whatever solution we settle on works for both tools in all cases.

> > which is not what I see in the PR. I'm concerned that this is a brittle solution given that if you run `make fmt`, it appears that isort will be run first and then black which I'm guessing is why the isort option we chose doesn't match up with the example in the README. If we want the same output as the output in the PR currently, we should be using option 7 which looks like:
> > ```
> > from third_party import lib1, lib2, lib3, ...  # NOQA
> > ```
> > 
> > 
> > If option 7 is what we want, my guess is that specifying line length as you did here might have actually fixed the conflict between black and isort that I saw previously (it did appear as if there were two separate conflicting line lengths as defaults in the two different tools).
> > What are your thoughts?

**Comment by mulkieran** [comment]
> > > @mulkieran I took a look at it and I have one concern. Are we confident that nested imports will work with black with the current multiline output that's selected? Furthermore, why is option 3 for multiline output giving different output from the documentation example? According to the README, 3 should result in something that looks more like:
> > > ```
> > > from third_party import (
> > >     lib1,
> > >     lib2,
> > >     lib3,
> > >     lib4,
> > > )
> > > ```
> > 
> > 
> > That's only if the output would actually take up multiple lines. We don't import enough things in
> > either of these libraries to have more imports than would fit in a single line. I experimented a
> > little with a PR for stratis-cli, where there are enough imports from a single module to trigger
> > the multi-line configuration. When there are, something like the example above is generated.
> 
> That will be a problem with `black` if I recall correctly. Feel free to verify that, but I'm pretty confident that that broke compatibility between the two tools. We should ensure that whatever solution we settle on works for both tools in all cases.
> 

It does not appear to cause any problems with black in the existing stratis-cli code base...I tried the experiment. Also, note that this set of configuration parameter's is black's recommended isort configuration file, and that the isort and black developers seem to communicate pretty regularly to maintain compatibility.

> > > which is not what I see in the PR. I'm concerned that this is a brittle solution given that if you run `make fmt`, it appears that isort will be run first and then black which I'm guessing is why the isort option we chose doesn't match up with the example in the README. If we want the same output as the output in the PR currently, we should be using option 7 which looks like:
> > > ```
> > > from third_party import lib1, lib2, lib3, ...  # NOQA
> > > ```
> > > 
> > > 
> > > If option 7 is what we want, my guess is that specifying line length as you did here might have actually fixed the conflict between black and isort that I saw previously (it did appear as if there were two separate conflicting line lengths as defaults in the two different tools).
> > > What are your thoughts?

**Comment by jbaublitz** [comment]
That's really interesting. If that's the recommended one, I'm willing to rely on their opinion here.

**Comment by mulkieran** [comment]
The problems that I have noticed with the current PRs:

* It is tedious to specify relative paths as local in the configuration file (as one must do ._misc, .._misc, etc.) and isort doesn't seem to be able to figure out that relative paths are by definition local. In order to deal with this, I made relative paths into absolute paths wherever possible. That caused the paths to be sorted somehow alphabetically, instead of according to specificity, e.g.:

```
  from ...mod1 import func1
  from ..mod2 import func2
  from .very_near_mod3 import func3
```
The specificity order is nice, because the lowest imports are local to the submodule in which the importing file is contained. This follows the same principle from less to greater specificity followed in the overall order, i.e., stdlib first, then third party, then first party.

Maybe I can fix this...what if isort understands globs?

**Comment by mulkieran** [comment]
We'll wait until December and use isort 4.3.4, if possible. The reason is that on Fedora 29, there is something wrong with the isort install and it doesn't yield you a working command-line tool. You can uninstall it via dnf and then install it via pip3 and this works fine. But pylint depends on isort at least in dnf, so when you uninstall isort you also uninstall pylint which is really inconvenient. On Fedora 30, which I will be upgrading to sometime next week, the dnf install of isort appears to provide a working command-line tool. So, once I've upgraded, there should be no obstacle.

**Comment by mulkieran** [comment]
This is blocked until I ugrade to f30, which I plan to do this afternoon.

**Comment by mulkieran** [comment]
Resolved by attached PRs.
