### ISSUE TITLE
Consider xfs tool for predicting the space requirements of a filesystem

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#401]
When we increase a filesystem's size, or wish to predict the space required by n filesystems to be put on a pool, it would be nice to have handy an xfs tool, akin to devicemapper's ```thin_metadata_size``` which would allow stratisd to know the space occupied by the thin pool metadata before hand.

**Comment by sandeen** [comment]
Can you elaborate on what you mean by "space requirements of a filesystem?"  Are you talking about metadata overhead, or something including the space consumed by files on that filesystem as well?

**Comment by mulkieran** [comment]
We should not expect to get precise information, due to the vagaries of device layout, etc.
