### ISSUE TITLE
Increase Rust recomended toolchain to 1.59

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#425]
- [x] Fix any newly introduced compiler or clippy errors
- [x] Give karma for f35 release: https://bodhi.fedoraproject.org/updates/FEDORA-2022-3bd845ce5a
  Make sure that all our Rust projects can be formatted, built, linted, and lightly tested with the new Rust toolchain. Skipped.
- [x] Bump current development toolchain in GitHub workflows
- [x] Extra: Give karma for f35 patch release; https://bodhi.fedoraproject.org/updates/FEDORA-2022-3bd845ce5a
  Make sure that all our Rust projects can be formatted, built, linted, and lightly tested with the new Rust toolchain. Any arch.

**Comment by mulkieran** [comment]
Starting Friday

**Comment by mulkieran** [comment]
F35 release of Rust is held up due to negative karma caused by non-terminating build.

**Comment by mulkieran** [comment]
Related bz for non-terminating compilation is here: https://bugzilla.redhat.com/show_bug.cgi?id=2058803.

**Comment by mulkieran** [comment]
We would want to do this on an s390x machine, because that is where the non-terminating bug has surfaced.

**Comment by mulkieran** [comment]
Resolved by merged PRs.

**Comment by mulkieran** [comment]
Upstream PR for Rust https://github.com/rust-lang/rust/pull/94505.

**Comment by mulkieran** [comment]
@bgurney-rh You can do the "Extra" step whenever you're ready.

**Comment by bgurney-rh** [comment]
Everything looks good; I just granted karma.

**Comment by mulkieran** [comment]
Closing once more...
