### ISSUE TITLE
Should we start releasing stratis-dumpmetadata?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#443]
It won't be generally useful to most people until we do.

- [x] https://github.com/stratis-storage/stratisd/issues/3148 (didn't do)

**Comment by drckeefe** [comment]
I like the idea of providing it, but do we provide this tool along with stratisd or a different tools package?

**Comment by mulkieran** [comment]
For downstream, e.g., Fedora, we could provide it as part of a subpackage.

**Comment by mulkieran** [comment]
We will provide it as a Fedora-only subpackage in the next release.

**Comment by mulkieran** [comment]
We can not release to f35, because the version of pretty-hex on f35 is too low. So, we should not actually release stratis-dumpmetadata until we are no longer releasing to f35.

**Comment by mulkieran** [comment]
We will carry on with this but make simpler alterations to the stratisd spec file which allow us to unconditionally release stratis-tools on all platforms.

**Comment by mulkieran** [comment]
We will work on a standard formula to add to the help text and the man pages to communicate the idea that the tools are intended to be useful for debugging but are unsupported.

**Comment by mulkieran** [comment]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=2137966
