### ISSUE TITLE
Do updates for F36 defaults that can be done before switching to f36 as development environment

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#456]
Most of these are f-strings. Apparently f-strings are a good deal faster than the other string formatting choices in Python.

Not done yet:
- [x] testing
- [x] ci
- [x] stratisd

In review:
- [x] stratis-cli

Some projects couldn't be updated fully before upgrading to f36, these are:
- [x] justbases
- [x] hs-dbus-signature

**Comment by mulkieran** [comment]
Also note that hs-dbus-signature is weird, and should be skipped.

**Comment by bgurney-rh** [comment]
There are no linting errors for 'consider-using-f-string' in dbus-signature-pyparsing.

**Comment by mulkieran** [comment]
I expect that we'll just disable the ```use-implicit-booleaness-not-comparison``` everywhere, but maybe pylint will get around to disabling it before we have to.

**Comment by mulkieran** [comment]
At this time, we can consider all repos are prepared to be upgrade to f36 defaults or they can't be upgraded without conflicting w/ f35 defaults, which is only justbytes.
