### ISSUE TITLE
pylint errors in current version of pylint on f36

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#462]
* consider-using-f-string lint interpreting modulus operator as string subsitution operator in some cases
See https://github.com/mulkieran/justbytes/blob/360a826116d2a5d8755a6df53b173980f743dc37/tests/test_deterministic/test_size/test_operations.py#L159. ~~This appears to be happening on version 2.17.3 of pylint.~~
* arguments-differ error in dbus-client-gen: this seems to be an error because the arguments don't differ
```
tests/_introspect.py:82:4: W0221: Number of parameters was 1 in 'XMLElement.name' and is now 1 in overridden 'Arg.name' method (arguments-differ)
tests/_introspect.py:92:4: W0221: Number of parameters was 1 in 'XMLElement.name' and is now 1 in overridden 'Interface.name' method (arguments-differ)
tests/_introspect.py:102:4: W0221: Number of parameters was 1 in 'XMLElement.name' and is now 1 in overridden 'Method.name' method (arguments-differ)
tests/_introspect.py:121:4: W0221: Number of parameters was 1 in 'XMLElement.name' and is now 1 in overridden 'Property.name' method (arguments-differ)
tests/_introspect.py:131:4: W0221: Number of parameters was 1 in 'XMLElement.name' and is now 1 in overridden 'Signal.name' method (arguments-differ)
```

**Comment by bgurney-rh** [comment]
Issue for the false positive `consider-using-f-string` lint when using a modulo operator on a string: https://github.com/PyCQA/pylint/issues/6689

**Comment by mulkieran** [comment]
So it turns out that the "arguments-differ" error was correct, because the arguments did differ. It's just that the message incorrectly identified the problem. It was not the number of arguments that differed, it was that the names of the arguments differed.

**Comment by mulkieran** [comment]
Closing. We reported the false positive, which was the real analysis bug. The other bug is just in an unhelpful error message, and I doubt that will ever get to the top of the pile.
