### ISSUE TITLE
Release stratis-cli 3.1.0-2 in Fedora

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#469]
* Add rpminspect.yaml file
* Diff with ci spec file and change as necessary (I don't think there's anything to do, but you may find something)

- [x] rawhide
- [x] f36: https://bodhi.fedoraproject.org/updates/FEDORA-2022-47f9073dc9
- [x] f35: https://bodhi.fedoraproject.org/updates/FEDORA-2022-faac4b4bce

**Comment by bgurney-rh** [comment]
The stratis-cli.spec file in Fedora is synchronized with the unified spec file in ci.
