### ISSUE TITLE
Start using rust-version in Cargo.toml

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#476]
This is the same as our lowest supported Rust toolchain which is the same as the msrv value in .clippy.toml. I do not see any evidence at present that clippy will respect the rust_version value in Cargo.toml and allow us to drop the .clippy.toml, but that may happen in time.

**Comment by mulkieran** [comment]
Oh, wait, I found a relevant issue: https://github.com/rust-lang/rust-clippy/issues/8746

**Comment by mulkieran** [comment]
We can do this after the next Rust update.

**Comment by mulkieran** [comment]
Blocked by https://github.com/stratis-storage/project/issues/516

**Comment by bgurney-rh** [comment]
We should be careful about the string.  If `rust_version` is used, this clippy warning will appear:
```
warning: unused manifest key: package.rust_version
```

I did a test run, adding this to the Cargo.toml file in stratisd, just below `edition = "2021"` (would this be a good place for the "rust-version" line?):

```
rust-version = "1.62.1"
```

...and I don't see any clippy warnings, and it builds successfully.

**Comment by mulkieran** [comment]
> We should be careful about the string. If `rust_version` is used, this clippy warning will appear:
> 
> ```
> warning: unused manifest key: package.rust_version
> ```
> 
> I did a test run, adding this to the Cargo.toml file in stratisd, just below `edition = "2021"` (would this be a good place for the "rust-version" line?):
> 
> ```
> rust-version = "1.62.1"
> ```
> 
> ...and I don't see any clippy warnings, and it builds successfully.

Next to the edition line in Cargo.toml is a good location.

You can go ahead and remove .clippy.toml file entirely as well, since all it contains is the msrv value, and that is redundant with this change.

**Comment by mulkieran** [comment]
I realized we can add the "# LOWEST SUPPORTED RUST TOOLCHAIN" annotation in the Cargo.toml file, so we should do that also.

**Comment by bgurney-rh** [comment]
Is it really worth the extra effort and indirection?  The `update_workflow_config.py` script usually operates on the path given to it, which is the `.github/workflows/*.yml` directory.  We would then have to add another set of paths to be updated, for one line, in four separate repositories.

**Comment by mulkieran** [comment]
> Is it really worth the extra effort and indirection? The `update_workflow_config.py` script usually operates on the path given to it, which is the `.github/workflows/*.yml` directory. We would then have to add another set of paths to be updated, for one line, in four separate repositories.

I'm going to separate this into two questions:
1. Is it worth it to annotate the Cargo.toml file? Definitely, because then we can see immediately what that value is supposed to represent for us. The only reason not to, is if clippy didn't like the comment, and clippy seems fine with it.
2. Should we update it, every six months, when we change our lowest supported toolchain, using the existing script, ```update_workflow_config.py```? I don't see why not; it turns out that that script is written so that it ought to be able to do the update without any problems, as far as I can tell.

**Comment by bgurney-rh** [comment]
There's another challenge: different formats (.yaml for the GitHub workflows, and .toml for Rust's Cargo.toml file).

The .toml file has the version string surrounded in double quotes.  This will currently fail with the `update_workflow_config.py` script.

**Comment by bgurney-rh** [comment]
I would need this in the ci repository:
```
diff --git a/misc_scripts/update_workflow_config.py b/misc_scripts/update_workflow_config.py
index ce21378..148fa25 100755
--- a/misc_scripts/update_workflow_config.py
+++ b/misc_scripts/update_workflow_config.py
@@ -82,8 +82,8 @@ def process_file(search_key, args):
     """
     filename = args.file
     outfilename = args.outfile
-    old_verstring = args.old_version + r"  " + search_key
-    new_verstring = args.new_version + r"  " + search_key
+    old_verstring = r'"' + args.old_version + r'"' + r"  " + search_key
+    new_verstring = r'"' + args.new_version + r'"' + r"  " + search_key
 
     output = search_file(search_key, old_verstring, new_verstring, filename)
 
```
...on the condition that the file being modified is a ".toml" file.

**Comment by mulkieran** [comment]
> I would need this in the ci repository:
> 
> ```
> diff --git a/misc_scripts/update_workflow_config.py b/misc_scripts/update_workflow_config.py
> index ce21378..148fa25 100755
> --- a/misc_scripts/update_workflow_config.py
> +++ b/misc_scripts/update_workflow_config.py
> @@ -82,8 +82,8 @@ def process_file(search_key, args):
>      """
>      filename = args.file
>      outfilename = args.outfile
> -    old_verstring = args.old_version + r"  " + search_key
> -    new_verstring = args.new_version + r"  " + search_key
> +    old_verstring = r'"' + args.old_version + r'"' + r"  " + search_key
> +    new_verstring = r'"' + args.new_version + r'"' + r"  " + search_key
>  
>      output = search_file(search_key, old_verstring, new_verstring, filename)
>  
> ```
> 
> ...on the condition that the file being modified is a ".toml" file.

I'm not convinced that's true. I think the ```str.replace``` method will handle a version string with enclosing quotation marks or without equally well, because it is replacing exactly one string with exactly another.

```
>>> str = "abdfg \"1.2\""
>>> str
'abdfg "1.2"'
>>> zed = str
>>> zed.replace("1.2", "3.4")
'abdfg "3.4"'
```
