### ISSUE TITLE
stratisd FTBFS in Fedora rawhide

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#487]
This problem is due to a new version of cryptsetup in rawhide + a known bug in bindgen: https://github.com/rust-lang/rust-bindgen/issues/753.

**Comment by mulkieran** [comment]
@jbaublitz Thanks for offering to work on the upstream bug. Do any of the workarounds described in the GitHub issue look like they might work for libcryptsetup's FTBFS problem?

**Comment by jbaublitz** [comment]
The work around is up in the PR linked below.

**Comment by mulkieran** [comment]
Fedora releases:
- [ ] rawhide: https://bodhi.fedoraproject.org/updates/FEDORA-2022-dcfb371f45

**Comment by mulkieran** [comment]
- [ ] rawhide: Done
- [ ] f36: https://bodhi.fedoraproject.org/updates/FEDORA-2022-9d1cef1fbb
- [ ] f35:

**Comment by mulkieran** [comment]
All tasks completed.
