### ISSUE TITLE
Question: expand pool after extending underlying md device 

### ISSUE THREAD

**Issue by ingothierack** [stratis-storage/project#50]
Is it possible to expand a pool if the underlaying device has changed?

I have added a new disk to an mdraid to expand it.
device md127 was expanded to 10.9 TB but this is currently not reflected in the stratis pool

```
  └─md127                                                                                         9:127  0 10.9T  0 raid5   
    └─stratis-1-private-210eb8dac6cb440993454dac6a885dae-physical-originsub                     253:2    0  7.3T  0 stratis 
      ├─stratis-1-private-210eb8dac6cb440993454dac6a885dae-flex-thinmeta                        253:3    0  7.4G  0 stratis 
      │ └─stratis-1-private-210eb8dac6cb440993454dac6a885dae-thinpool-pool                      253:5    0  7.3T  0 stratis 
```
 
Is there a way to make the additional space visible to stratis?

**Comment by mulkieran** [comment]
> By any chance, even to do it now manually(edit some files or something likes this), to tell stratis it has more space available?
> 
> Had the mdraid expanding done a few times in the past on plain lvm based setup. That was one of the main reasons, to go this way, and not in the ZFS or btrfs direktions for raid handling. So i thougth, i had more flexibility with stratis in this way.
> 
> If there is currently no way, i had to go with new disks and create a new pool, than copy over the data.

There should be a way to edit the metadata that should work, at least in your constrained situation, with only one device. I expect to be able to take a closer look on Thursday.

**Comment by mulkieran** [comment]
@mulkieran ping

**Comment by mulkieran** [comment]
Just a preliminary note: The size of the device when it was claimed is part of the signature buffer data. If the new size is less than the old size, there is an error on setup. If the new size is greater, the extra space is just ignored. The important part is still the variable length metadata.

**Comment by ingothierack** [comment]
question about this. By any chance, to see here within the next weeks any improvement? Even as spoken before, a manual process would be ok, until a final implementation is finished.

**Comment by ingothierack** [comment]
Ping on this feature/Issue. 
My storage runs slowly down :(

Maybe some progress on this for october?

**Comment by ingothierack** [comment]
Any news on this topic? In the current stage this means, i had to replace the current pool with a new one with bigger drives.

**Comment by ingothierack** [comment]
New year, hopfully more luck on this topic.
Would be grate to see here some improvement.

**Comment by mulkieran** [comment]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1768933

**Comment by mulkieran** [comment]
Blocked by #298

**Comment by mulkieran** [comment]
Now blocked by start/stop pools work.
