### ISSUE TITLE
Release stratisd 3.2.2 in Fedora

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#508]
- [x] rawhide: https://bodhi.fedoraproject.org/updates/FEDORA-2022-2dc84c38b1
- [x] f37: https://bodhi.fedoraproject.org/updates/FEDORA-2022-a101964616
- [x] f36: https://bodhi.fedoraproject.org/updates/FEDORA-2022-2922dc432c
- [x] f35: https://bodhi.fedoraproject.org/updates/FEDORA-2022-dc4718852d

**Comment by bgurney-rh** [comment]
All tests (from the testing repository, tag "v3.2.0") passed for the F35 and F36 updates.

**Comment by bgurney-rh** [comment]
All tests (from the testing repository, tag "v3.2.0") passed for the F37 update.
