### ISSUE TITLE
Retain idempotency in D-Bus API but remove idempotency from the CLI

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#51]
The idea originally was that it would be nice to be able to script the CLI, so it would be reasonable to make actions idempotent. But this doesn't seem comfortable for most people. So, we want to retain idempotency in the daemon, but lose it in the CLI.

An example is given in bz: https://bugzilla.redhat.com/show_bug.cgi?id=1687869.

If the device is already attached to the pool, the CLI considers that the action succeeded. Users would prefer an error message, and an error code. There are other instances of the same throughout the CLI.

We have an implementation plan for this which requires the CLI to interpret the results of the D-Bus call, and report an error as appropriate. In one instance, though, the daemon is returning an error, i.e., it is not idempotent, though it should be. So this is also a bug that needs to be fixed, which is what makes this a project-wide issue.

**Comment by jbaublitz** [comment]
I've reproduced the issue and it seems the exact commands described in the bugzilla will error on the first command but succeed on the second. If a pool named `test_pool` exists containing a block device `/dev/sda`, `stratis pool create test_pool /dev/sda` will fail with the message `ALREADY EXISTS: test_pool` while `stratis pool add-data test_pool /dev/sda` will succeed and exit 0. I'll take a look and try to make commands consistently fail when using the CLI if the resources already exist.
