### ISSUE TITLE
Correct saving of on-disk metadata. Document.

### ISSUE THREAD

**Issue by agrover** [stratis-storage/project#513]
see also stratis-storage/stratisd#583 and [this discussion](https://github.com/stratis-storage/stratis-docs/issues/64#issuecomment-337403753).

We need to determine when saving state to on-disk metadata is correct wrt power failures, for MDV state as well. It should be centralized in the engine or pool code rather than being invoked explicitly in e.g. the D-Bus API code.

This should be written up in the design doc too. Proper handling of this is something potential contributors and users will want to see has been considered and implemented correctly.

**Comment by mulkieran** [comment]
obsolete.
