### ISSUE TITLE
Add back in ignores for .symtab errors

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#577]
We believe that the rpminspect bug https://github.com/rpminspect/rpminspect/issues/1069 has been fixed, so we can add back in the ignores in the rpminspect.yaml file. We will have to keep the ignores in until https://bugzilla.redhat.com/show_bug.cgi?id=2166149 has been addressed. See https://github.com/stratis-storage/project/issues/567#issuecomment-1410848132 for additional details.

**Comment by mulkieran** [comment]
Note that the suggestion was made in the attached bz to "%undefine _include_minidebuginfo". There is some documentation about that here: https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/buildflags.md . But I'm not sure what that will do.

**Comment by mulkieran** [comment]
We have verified that the debuginfo ignores are now being recognized.

**Comment by bgurney-rh** [comment]
The rpminspect.yaml file in the Fedora Rawhide release stratisd-3.5.1-2.fc39 has been updated to add the `debuginfo` ignore.

A matching pull request has been created in stratis-storage/ci#380
