### ISSUE TITLE
Python 3.7.3 to 3.7.4 seems to break yapf

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#58]
In our CI for Python, I discovered when trying to reproduce locally the formatting changes needed for CI to pass in `stratis-cli` that Python 3.7.1 with yapf 0.21.0 does indeed reproduce the same CI formatting changes. Python 3.7.4 does not. There seem to be a significant number of changes in formatting from Python 3.7.3 to 3.7.4 which happens all while yapf is at 0.21.0 based on the requirements.txt file. We should investigate if this means yapf also needs an upgrade once we get to Python 3.7.4.

**Comment by mulkieran** [comment]
We are resolving this by moving to black, see issue #35.
