### ISSUE TITLE
clevis commands that stratisd uses that require cracklib-dicts package to be installed are failing in CI

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#581]
We run a bunch of tests on f37 containers that use clevis, and, as of Feb 23, some of these tests are failing.

On Feb 22nd, these tests ran and succeeded. The difference is that on Feb 22nd, cracklib-dicts was recognized as a weak dependency of something and installed in our tests-with-tang in main.yaml, but on Feb 23rd, it wasn't.

It should have been recognized as a weak dependency of clevis and installed, since the clevis spec file Recommends it.

All test errors look roughly like this:

```
thread 'engine::strat_engine::engine::test::clevis_loop_test_keyring_unbind_rollback' panicked at 'called `Result::unwrap()` on an `Err` value: Msg("Command failed: cmd: \"/usr/bin/clevis\" \"luks\" \"bind\" \"-y\" \"-d\" \"/dev/loop3\" \"-k\" \"/run/stratisd/ns_mounts/Kc4aW8D6tpt8HBfo/test-description-for-stratisd\" \"-t\" \"2\" \"tang\" \"{\\\"url\\\":\\\"tang\\\"}\", exit reason: 1 stdout:  stderr: /usr/share/cracklib/pw_dict.pwd.gz: No such file or directory\n/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory\n/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory\nError: Password generation failed - required entropy too low for settings\nUnable to generate a new key\nError adding new binding to /dev/loop3\n")', src/engine/strat_engine/tests/crypt.rs:50:12
```

We think this may be a bug in dnf. But also, we wonder if, since it doesn't seem like we can turn off the use of password dict file when invoking these clevis-luks commands, if it would be possible to make cracklib-dicts Required in the clevis Fedora spec file again.

**Comment by drckeefe** [comment]
@sergio-correia 
Thoughts?

**Comment by sergio-correia** [comment]
> @sergio-correia Thoughts?

I wonder if it's related to https://bugzilla.redhat.com/show_bug.cgi?id=2158891?

**Comment by mulkieran** [comment]
@sergio-correia That seems quite plausible, but libpwquality doesn't seem like it has ever been installed for our CI. I'm looking at a working run example: https://github.com/stratis-storage/stratisd/actions/runs/4244077328/jobs/7377682555 and also the non-working run: https://github.com/stratis-storage/stratisd/actions/runs/4257245609/jobs/7407146375 .

**Comment by mulkieran** [comment]
Extra Note: So, the stated reason for downgrading cracklib-dicts dependency to Recommends is: "It's a 10 MB dependency, and isn't needed if dictcheck = 0 in /etc/security/pwquality.conf."

**Comment by mulkieran** [comment]
Probably related: https://github.com/rpm-software-management/dnf/issues/1868

**Comment by mulkieran** [comment]
So, this is a sponatenously manifesting dnf bug (characterized by arbitrarily failing to install some Recommends dependencies, but not others and is really a bug in the solver that dnf uses). There is both an upstream GitHUb issue and a linked bugzilla.

So, I think libpwquality should make the dependency a Requires again. Complained in https://bugzilla.redhat.com/show_bug.cgi?id=2158891, and so I'm totally closing the loop.

**Comment by mulkieran** [comment]
Assuming nothing gets fixed, though, we'll have to decide if we'll need to put a Recommends in our stratisd spec file.

**Comment by mulkieran** [comment]
No movement on the bz, let's put a Recommends in our stratisd spec file.

**Comment by mulkieran** [comment]
One possible fix by stratisd is to change the ```Recommends cracklib-dicts``` that we tried out in https://github.com/stratis-storage/ci/pull/386 into a conditional Requires, something like ```
Requires: (cracklib-dicts if clevis-luks)```

**Comment by mulkieran** [comment]
bz filed: https://bugzilla.redhat.com/show_bug.cgi?id=2177857 .

**Comment by mulkieran** [comment]
We have an explanation in the following bz comment: https://bugzilla.redhat.com/show_bug.cgi?id=2177857#c4. libpwquality was part of the default container image, w/out cracklib-dicts installed, so installation of clevis with ```exclude_from_weak_autodetect``` true, as it is by default, would cause cracklib-dicts not to be installed. We could argue that this is actually a bug in the container. We can argue that there is a bug in the container, because not installng cracklib-dicts only makes sense if the value of ```dictcheck``` in ```/etc/security/pwquality.conf``` is 0 (which it doesn't seem to be in the container, the dictcheck field is commented out, instead).

We could file a bug against whoever supplies the container.

**Comment by mulkieran** [comment]
I do not know how to file an issue against the container, and it may not be worth our while to do so, so closing.
