### ISSUE TITLE
Increase recommend Rust toolchain to 1.68.0

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#587]
- [x] Fix any newly introduced compiler or clippy errors:
  - [x] devicemapper-rs
  - [x] libblkid-rs
  - [x] libcryptsetup-rs
  - [x] stratisd: omit ```derive_hash_xor_eq``` lint

- [x] Give karma for f37 release: https://bodhi.fedoraproject.org/updates/FEDORA-2023-44999277b5
 
- [x] Bump current development toolchain in GitHub workflows
  - [x] devicemapper-rs
  - [x] libblkid-rs
  - [x] libcryptsetup-rs
  - [x] stratisd
  - [x] stratis-docs (because now we need to build zola from source)

**Comment by bgurney-rh** [comment]
No compiler or clippy errors in the projects other than stratisd.

For stratisd, there's an issue caused by the rename of `clippy::derive_hash_xor_eq` to `clippy::derived_hash_with_manual_eq`.  Removing the allow in 1.68.0 results in no clippy errors in 1.68.0, but errors in 1.67.1.
