### ISSUE TITLE
libcryptsetup-rs 0.7.0 release

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#608]
We are able to do this immediately after https://github.com/stratis-storage/libcryptsetup-rs/pull/282 if that is helpful.

~~We can release in Fedora w/out any conflict w/ stratisd.~~

Upstream:
- [x] libcryptsetup-rs-sys: 0.2.4
- [x] libcryptsetup-rs: 0.7.0

**Comment by jbaublitz** [comment]
This needs to wait a little longer while I ensure that there's nothing else that should go out in this release.

**Comment by mulkieran** [comment]
Also, it would be nice, although not necessary, to leave out the Cargo.toml patch introduced in https://github.com/stratis-storage/libcryptsetup-rs/pull/283 .

**Comment by mulkieran** [comment]
We can release whenever we're ready now.

**Comment by mulkieran** [comment]
Also release libcryptsetup-rs-sys v0.2.4.
