### ISSUE TITLE
Error when trying to bind TPM2 to Stratis pool

### ISSUE THREAD

**Issue by arnavyc** [stratis-storage/project#629]
Distribution: Arch Linux
Versions:
- `stratis --version` = `3.5.1`.
- Version of clevis is `18-2` according to `pacman -Qi clevis`.

When trying to bind TPM2 to Stratis pool, I got -

```
# stratis pool bind tpm2 <name_of_pool>
Execution failed:
stratisd failed to perform the operation that you requested. It returned the following information via the D-Bus: ERROR: Command failed: cmd: "/usr/sbin/clevis" "luks" "bind" "-d" "/dev/nvme0n1p8" "-e" "1" "-t" "2" "tpm2" "{}", exit reason: 2 stdout:  stderr: 
Usage: clevis luks bind [-y] [-f] [-s SLT] [-k KEY] [-t TOKEN_ID] -d DEV PIN CFG

Binds a LUKS device using the specified policy:

  -f           Do not prompt for LUKSMeta initialization

  -d DEV       The LUKS device on which to perform binding

  -y           Automatically answer yes for all questions

  -s SLT       The LUKS slot to use

  -t TKN_ID    The LUKS token ID to use; only available for LUKS2

  -k KEY       Non-interactively read LUKS password from KEY file
  -k -         Non-interactively read LUKS password from standard input
```

It seems that Stratis is passing `-e` flag to `clevis luks bind`, which according to https://man.archlinux.org/man/clevis-luks-bind.1.en is not a valid option.

**Comment by mulkieran** [comment]
Does the comment in Fedora stratisd spec file help:

```
# stratisd does not require clevis; it can be used in restricted environments
# where clevis is not available.
# If using encryption via clevis, stratisd requires the instance of clevis
# that it uses to have been built in an environment with cryptsetup >= 2.6.0.
```

It's a requirement that can't be enforced in the spec file. The key thing is that Clevis has to have been _built_ with cryptsetup >= 2.6.0 in its build environment. Just running it with cryptsetup >= 2.6.0 in the environment will not resolve this problem.

**Comment by arnavyc** [comment]
After looking into clevis, I noticed that `-e` option was introduced in latchset/clevis@71869cb714eb31c00ac5a05698c830ff549cb1dc which was incorporated into version 19 of clevis. However Arch (surprisingly) hasn't updated clevis and the tool is still at v18 in Arch. The version 19 is still in testing repos. I have filled a bug report with bugs.archlinux.org (https://bugs.archlinux.org/task/79161).

**Comment by mulkieran** [comment]
Right. I think that the ```-e``` change was backported to version 18 of clevis in Fedora, but obviously not in Arch. I believe that the cryptsetup version requirement will still hold for version 19 of clevis. I'll close this issue, but feel free to re-open if something else comes up.
