### ISSUE TITLE
Track and report snapshot origin relation

### ISSUE THREAD

**Issue by bmr-cymru** [stratis-storage/project#643]
The Stratis design document states that the origin of snapshots is tracked in the MDV:

```
10.2.4 Thin Volumes

Stratis also enables creating a new volume as a read/write snapshot of an
existing volume. Although the underlying implementation does not require
maintaining the relation between a snapshot and its origin, Stratis records this
relation in its metadata. This relation may be of use to users who may, for
example, use snapshots for backups and may make use of the origin information
to identify a particular backup snapshot to restore from
```

Although looking at the metadata recorded on a test system this doesn't seem to be the case, e.g.:

```
[root@localhost mnt]# cat filesystems/fe2020520fae4ebda4afe14c65895063.json
{"name":"fs1","uuid":"fe202052-0fae-4ebd-a4af-e14c65895063","thin_id":0,"size":2147483648,"created":1683036419}
[root@localhost mnt]# cat filesystems/b2b8bc13eaf343978040382e238c013c.json
{"name":"fs1-snap","uuid":"b2b8bc13-eaf3-4397-8040-382e238c013c","thin_id":1,"size":2147483648,"created":1691166865}
```

It would be useful for the reasons given in the design document if this relationship was recorded and exposed in stratis-cli command output.

**Comment by mulkieran** [comment]
Our Stratis filesystems are all first class, so every filesystem is potentially a parent or a snapshot, but every snapshot only has one origin. So, it should be straightforward to include an optional field, e.g., ```parent``` for every filesystem and set that optional field to the UUID of the origin on snapshot creation. Then, exposing this information on the D-Bus as on optional field is also straightforward.

**Comment by mulkieran** [comment]
For stratis-cli command output, we have some options. One is to introduce a filesystem detail view, which we have been considering for a while, anyhow.
