### ISSUE TITLE
Provide a way to map Stratis device-mapper names to pool/filesystem

### ISSUE THREAD

**Issue by bmr-cymru** [stratis-storage/project#650]
Administrators are encouraged to use the `/dev/<pool>/<filesystem>` symlinks managed by udev and this provides a straightforward way to access Stratis devices according to the names assigned to them.

In some situations (for example parsing `/proc/self/mounts` to map a mount point to a device) only the name from `/dev/mapper` is known, for e.g.:

```
# grep stratis-1 /proc/self/mounts 
/dev/mapper/stratis-1-50588b687c30473f813e35bce4251185-thin-fs-68e24b8af98c4b5580ab59ca440f0af1 / xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=32k,sunit=2048,swidth=2048,noquota 0 0
```

This yields the device-mapper name for the device via the `/dev/mapper` symlink and it's trivial to extract the pool and filesystem UUID from the string however this requires knowledge of the naming scheme (which could potentially change in future).

It would be useful to have either a mechanism to directly map these DM names back to the pool/filesystem they belong to, or at least to be able to properly decode the two UUID values contained in the name.

The `dmsetup` command supports a `splitname` command that can parse LVM2 device-mapper names.

For e.g. the device-mapper name `appdata-datavol1--test` corresponds to the VG/LV `appdata/datavol1-test`. The `splitname` command correctly handles the escaped `-` character:

```
# dmsetup splitname appdata-datavol1--test
VG      LV            LVLayer
appdata datavol1-test        
```

Extending `splitname` to understand Stratis naming would be one way forward or a mechanism provided by Stratis would also work for the case of mapping a mount point back to the device from which it is mounted.

**Comment by bmr-cymru** [comment]
Having looked at the splitname implementation in dmsetup (and realising the it supports exactly one subsystem: LVM), I'm inclined to agree.

**Comment by bmr-cymru** [comment]
The end result I'm looking for is a DM name -> pool/filesystem name but I'm fine with breaking that down into steps if needed (i.e. extract the pool and fs UUID first and then convert those into names).

**Comment by mulkieran** [comment]
We have two domains, ```/dev/mapper/<dm device name>```-names, called D,  and ```/dev/<poolname>/<filesystem name>``` names, called S and a bijection between the two, and we need a function from S to D.

Our two options are using:

1. very simple scripts like those in https://github.com/stratis-storage/stratisd/tree/master/src/bin/udev-lib (we could even make them completely statically linked if that seemed desirable) that just parse out the names OR
2. else ones that compile in most of stratisd, like https://github.com/stratis-storage/stratisd/blob/master/src/bin/stratis-utils.rs .

For (1) we would have to rely on external testing to make sure we didn't get out of sync. This will be very hard to arrange in a sensible way.

For (2) we would make a type which was something like ```StratisDmId``` which would implement Display and FromStr.  The ```format_*_ids``` methods would all be implemented via the ```fmt()``` method on the ```StratisDmId``` implementation., which could all still return the ```DmNameBuf``` and ```DmUuidBuf``` results as they do now. To use this, the script would just pass a string to be parsed by the ```StratisDmId``` implementation. We could easily add tests, probably by proptest, which will, always, verify that the functions map correctly. The cost is a bigger executable. ```StratisDmId``` would have parts, corresponding to the different parts of the DM name. The drawback is that this seems like seriously extra work for a mapping between filesystems links only. Will we have any other need to extract Stratis information from a DM name in future? Very likely, actually.

Right now I'm favoring (2), although it is heavier, and the implementation will be a bit boring.

**Comment by mulkieran** [comment]
Note that the command-line utility must be placed in stratis-utils not in -tools which is a separate package. Because this utility will be invoked by other apps while stratisd is running.

**Comment by mulkieran** [comment]
I am not averse to giving stratis-utils the same treatment as stratisd-tools because the treatment makes testing much more convenient.

**Comment by mulkieran** [comment]
Note that we already have a function, ```path_to_mount_filesystem``` to assist the D-Bus in putting out this info, this function invokes ```devlinks::filesystem_mount_path```.

**Comment by mulkieran** [comment]
Given all the ways we are forced to duplicate generating this mapping, one more way might not matter. And testing might actually be the way to go. This beats making a more heavyweight mechanism that we can not reuse.
