### ISSUE TITLE
Release Stratis 3.6.0

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#673]
Up-to-date: but pending Fedora release: 2022-10-31 estimated date
 * rust-libblkid-rs-sys: 0.2.0
 * rust-libblkid-rs: 0.3.1

devicemapper:
* devicemapper-sys: 0.1.5 -> devicemapper-rsy: 0.2.0 (bindgen bump, already upstream)
* devicemapper: 0.33.6 -> 0.34.0 (bitflags bump) https://github.com/stratis-storage/devicemapper-rs/pull/887

libcryptsetup:
* libcryptsetup-rs-sys: 0.2.4 -> 0.3.0 (bindgen bump, already upstream)
* libcrytpsetup-rs:  0.9.0 -> 0.9.1: https://github.com/stratis-storage/libcryptsetup-rs/pull/332

- [x] stratisd: https://github.com/stratis-storage/stratisd/pull/3478
* bump libcryptsetup-rs and libcryptsetup-rs-sys and devicemapper version requirements in Cargo.toml: https://github.com/stratis-storage/stratisd/pull/3474
* Run packit on rawhide, as we should be able to complete a release into rawhide by end of today: https://github.com/stratis-storage/stratisd/pull/3477
* Fix up dependency lower bounds and update to avoid audit of any sort: https://github.com/stratis-storage/stratisd/pull/3481
* Update to cargo vendor-filterer configuration: https://github.com/stratis-storage/stratisd/pull/3479
* Fix up excludes in Cargo.toml: https://github.com/stratis-storage/stratisd/pull/3482

- [x] stratis-cli: https://github.com/stratis-storage/stratis-cli/pull/1034

- [x] testing: https://github.com/stratis-storage/testing/pull/227

- [x] blog post: https://github.com/stratis-storage/stratis-docs/pull/337

- [x] blog post posted: https://stratis-storage.github.io/stratis-release-notes-3-6-0/

- [x] Update introspection data:

- [x] https://github.com/stratis-storage/ci/issues/484

- [x] Release stratisd 3.6.1:
  * https://github.com/stratis-storage/stratisd/pull/3487
  * https://github.com/stratis-storage/stratisd/pull/3490

- [x] Fedora:
  - in one side-tag, in the following order:
    - libcryptsetup-rs-sys: 0.3.0
    - libcryptsetup-rs: 0.9.1
    - devicemapper-sys: 0.2.0
    - devicemapper: 0.34.0
    - stratisd: 3.6.0
    - stratis-cli: 3.6.0

  - [x] rawhide: https://bodhi.fedoraproject.org/updates/FEDORA-2023-9c1078a92c
  - [x] f39: https://bodhi.fedoraproject.org/updates/FEDORA-2023-c464ef1f0a
  - [x] f38: https://bodhi.fedoraproject.org/updates/FEDORA-2023-077058070e
  - [x] f37: https://bodhi.fedoraproject.org/updates/FEDORA-2023-ffa77eee82

- [x] Release stratisd 3.6.2:
  - [x] Upstream: https://github.com/stratis-storage/stratisd/pull/3497
  - [x] Fedora:
    - [x] rawhide: https://bodhi.fedoraproject.org/updates/FEDORA-2023-372db315e7
    - [x] f39: https://bodhi.fedoraproject.org/updates/FEDORA-2023-a0a693b060
    - [x] f38: https://bodhi.fedoraproject.org/updates/FEDORA-2023-8cb9c8b7e0
    - [x] f37: https://bodhi.fedoraproject.org/updates/FEDORA-2023-b4c13836fa

 - [x] Orphan rust-libcryptsetup-rs0.8
    * https://bugzilla.redhat.com/show_bug.cgi?id=2246615
    * https://src.fedoraproject.org/rpms/rust-libcryptsetup-rs0.8 

- [x] Email to stratis-devel

- [x] Update Packit tests to run on more than rawhide, using aliases: https://packit.dev/docs/configuration#aliases
  * https://github.com/stratis-storage/stratisd/pull/3502
  
- [x] Retire rust-libcryptsetup-rs0.8: https://fedoraproject.org/wiki/How_to_remove_a_package_at_end_of_life
  - [x] rawhide
  - [x] f39
  - [x] f38
  - [x] f37 

- [x] Release stratisd 3.6.3:
  - [x] Fedora:
    - [x] rawhide: https://bodhi.fedoraproject.org/updates/FEDORA-2023-805878885f
    - [x] f39: https://bodhi.fedoraproject.org/updates/FEDORA-2023-d2d2de2e98
    - [x] f38: https://bodhi.fedoraproject.org/updates/FEDORA-2023-ab930d1c58

**Comment by bgurney-rh** [comment]
The Fedora updates listed above for F39, F38, and F37 have been updated to use stratisd-3.6.1. 

(Fedora Rawhide update for stratisd-3.6.1-1.fc40 is pushed to stable: https://bodhi.fedoraproject.org/updates/FEDORA-2023-f32820261d )
