### ISSUE TITLE
Update FEDORA_RELEASE environment variable for check-fedora-versions make invocation in GitHub Actions

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#676]
Currently, in most cases, the FEDORA_RELEASE environment variable is set to rawhide, f38, and f37. We should instead set it to rawhide, f39, and f38.

In future, we would like either:
* To use a completely different rpm based scheme using official rust2rpm functionality, i.e., for each direct dependency in Cargo.toml, find the satisfying Fedora package and see if that package is a legacy package. If so, then we are behind. etc.
* Maybe use fedora release aliases, similarly to what Packit does

**Comment by bgurney-rh** [comment]
There is also a FEDORA_RELEASE environment variable in the ci repository, in container_files/Makefile.  Should that be updated from 38 to 39?

**Comment by mulkieran** [comment]
> There is also a FEDORA_RELEASE environment variable in the ci repository, in container_files/Makefile. Should that be updated from 38 to 39?

@bgurney-rh Thanks for pointing that out. We should just remove those files, since we no longer use the containerize tang server, since we moved all that to Packit based testing. PR is up: https://github.com/stratis-storage/ci/pull/490 .
