### ISSUE TITLE
Fix up Python formatting failures in all relevant projects

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#690]
black in f39 was just updated from 23.7 to 24.1.

**Comment by bgurney-rh** [comment]
No changes were necessary in the following repositories: ci, dbus-python-client-gen, dbus-signature-pyparsing, into-dbus-python, justbytes, hs-dbus-signature.

**Comment by bgurney-rh** [comment]
No changes necessary in pyudev.
