### ISSUE TITLE
Unclear error message when trying to add an existing member as cache dev

### ISSUE THREAD

**Issue by agrover** [stratis-storage/project#76]
It looks like this has the proper behavior -- attempting to add a data dev already in a pool as a cache dev fails, whereas trying to (re)add it as a data dev idempotently succeeds. But the error message is not great. It would be better if it said something about the blockdev already being a member of the pool, but in a different tier.

```
# stratis pool create test_pool /dev/sdj
# stratis pool add-cache test_pool /dev/sdj
Execution failure caused by:
ERROR: Device /dev/sdj with pool UUID is unknown to pool
# stratis blockdev
Pool Name  Device Node    Physical Size   State  Tier
test_pool  /dev/sdj            9.10 TiB  In-use  Data
# stratis pool add-data test_pool /dev/sdj
# stratis blockdev
Pool Name  Device Node    Physical Size   State  Tier
test_pool  /dev/sdj            9.10 TiB  In-use  Data
```

bz: https://bugzilla.redhat.com/show_bug.cgi?id=1642393.

**Comment by mulkieran** [comment]
Closed by https://github.com/stratis-storage/stratis-cli/pull/358.
