### ISSUE TITLE
Add CLI blackbox tests of a normal sort

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#79]
Once #70 has been completed, it will be time to add in reasonable tests for the CLI. We can consider this issue blocked by #70 at this time. We can use the how-to for inspiration, maybe: https://stratis-storage.github.io/howto/.

**Comment by mulkieran** [comment]
We should not use any of the function in ```testlib/stratis.py``` which wrap stratis command-line invocations. Instead, we should use only ```exec_command``` to specify the stratis command-line and the expected return code.

It will be also useful to use ```STRATIS_CLI```, ```p_n```, and ```f_n```, in order to obtain the absolute path of stratis and the ability to generate random pool and filesystem names.

**Comment by mulkieran** [comment]
#70 has been accomplished, so this is unblocked now.

**Comment by bgurney-rh** [comment]
From the stratis man page, here's a quick list of the "non-volatile" user commands (i.e.: the commands that only read and report status and/or settings, and don't modify any Stratis devices):

```
stratis pool list
stratis filesystem list [pool_name]
stratis blockdev list [pool_name]
stratis daemon redundancy
stratis daemon version
```

And here are the "volatile" commands (the commands that modify a Stratis device):
```
stratis pool create <pool_name> <blockdev> [<blockdev>..]
stratis pool rename <old_pool_name> <new_pool_name>
stratis pool destroy <pool_name>
stratis pool add-data <pool_name> <blockdev> [<blockdev>..]
stratis pool add-cache <pool_name> <blockdev> [<blockdev>..]
stratis filesystem create <pool_name> <fs_name> [<fs_name>..]
stratis filesystem snapshot <pool_name> <fs_name> <snapshot_name>
stratis filesystem destroy <pool_name> <fs_name> [<fs_name>..]
stratis filesystem rename <pool_name> <fs_name> <new_name>
```

**Comment by mulkieran** [comment]
Grabbing this temporarily in order to do some preparatory cleanup.

**Comment by mulkieran** [comment]
#337 was merged, so I'm taking myself off this issue.
