### ISSUE TITLE
Gradually add in useful clippy lints that we currently don't check for

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#97]
Ultimately this will be helpful. But we might have to add them in gradually. Some are hard to fathom.

**Comment by mulkieran** [comment]
Well, stratisd has 40 warnings, and devicemapper has 0.

**Comment by mulkieran** [comment]
```needless_borrow```, the one I was really interested in, is in the nursery. devicemapper has 0 needless borrows, stratisd seems to have about 80.

**Comment by mulkieran** [comment]
@jbaublitz If you find a lint in the nursery or pedantic categories that you find especially valuable, please feel free to propose it.

**Comment by jbaublitz** [comment]
The only ones that jump out at me immediately are some of the integer lints around wrapping and lossy conversions. It could be interesting to see if we guard against that everywhere.

**Comment by mulkieran** [comment]
@jbaublitz If you want to go ahead and try one of those out in a PR go right ahead.

**Comment by jbaublitz** [comment]
I'm not sure that the suggested lints are going to help here. Most of the warnings are about `u64` to `usize` and given this is only a problem on 32-bit systems, I don't think we'll get much benefit out of this as stratisd is not meant for 32 bit. I don't think I can add anything in terms of lints to what we already have.

**Comment by mulkieran** [comment]
Ok! We'll let this sit until something does come up.

**Comment by mulkieran** [comment]
I'm thinking of going through these lints and turning on all the ones that make obvious sense and that we already don't infringe, in order to prevent future infringements. Then we can work on the more tricky ones, that we are actually infringing and that are important to us.

**Comment by mulkieran** [comment]
We stopped trying to keep our PEDANTIC LINTS variable in the Makefile up-to-date and maintained a long time ago, because we got a really limited benefit from doing that. Maybe someday we'll remove that variable entirely and rely on clippy processes to promote the pedantic lints to more interesting categories.
